### ISSUE TITLE
Unable to adjust image height via batch script

### ISSUE THREAD

**Issue by birndle** [igvteam/igv#160] opened 2015-07-10 20:42 UTC
Hello,

I'm running IGV with a batch file in order to take many screenshots at once. I would like to increase the height of my screenshots so that I can see more of the reads. I thought maxPanelHeight would do the trick, but it's not working as I expected. It affects which reads I see, but the height of the screenshot remains the same. (see attached images)

I'm running the following command: java -Xmx1024M -jar ~/bin/igv-2.3.52/igv.jar -b batch
where batch is as follows:

new
genome hg19
load test.bam
snapshotDirectory screenshots
goto chr12:56679722
maxPanelHeight 2000
snapshot shot.png
exit

![shot_500](https://cloud.githubusercontent.com/assets/7928926/8628594/63d9d364-2722-11e5-967b-3782e10c1557.png)
![shot_2000](https://cloud.githubusercontent.com/assets/7928926/8628595/63da9aba-2722-11e5-8442-081e7b8400ef.png)

The first shot is with maxPanelHeight 500, and the second maxPanelHeight 2000. Is this the expected behavior of maxPanelHeight? Or am I correct in assuming that increasing maxPanelHeight should increase the number of viewable reads?

**Comment by jrobinso** [comment] 2015-07-11 15:22
Hi,

maxPanelHeight should work as you expect it to.   I will investigate.

Jim

**Comment by birndle** [comment] 2015-07-13 16:22
Thanks for the quick response. I was using version 2.3.52 of IGV, but after switching to an older version, 2.0.35, the problem goes away. Hopefully, this will provide some hint as to what's going wrong.

**Comment by jrobinso** [comment] 2015-07-13 17:27
Hi,  I just tested this with the latest version (2.3.57) and can't reproduce the problem.   Try the script below, and tell me if you see the attached screenshot.
maxPanelHeight 2000
load http://www.broadinstitute.org/igvdata/BodyMap/hg19/IlluminaHiSeq2000_BodySites/brain_merged/accepted_hits.bam
goto chr8:128,746,315-128,755,680
snapshot
new


![chr8_128 746 315_128 755 680](https://cloud.githubusercontent.com/assets/933148/8655978/cca21a0e-2962-11e5-97b2-3ce899f20df4.png)
.

**Comment by bw2** [comment] 2015-07-20 23:26
Hi Jim, 

I'm seeing the same thing with version 2.3.57 (and also v2.3.46 which I had lying around), running on a MacOSX laptop.

When I run  ```java -jar ~/bin/igv-2.3.57/igv.jar -b batch.txt``` where `batch.txt` is:
```
maxPanelHeight 2000
load http://www.broadinstitute.org/igvdata/BodyMap/hg19/IlluminaHiSeq2000_BodySites/brain_merged/accepted_hits.bam
goto chr8:128,746,315-128,755,680
snapshot
new
```
I get a really small IGV window, and the following log output:

![image](https://cloud.githubusercontent.com/assets/6240170/8789741/a7eea338-2f13-11e5-96d0-57c367186a75.png)

If I manually resize the window to a bigger size, close it, and then run the command again, it will open to the last size it had before I closed it.  This is ok as a workaround on the laptop, but doesn't help when I run on a linux cluster where I run inside Xvfb to avoid the Headless error. 

Also, when I make the window bigger, I see that the bam track actually wasn't loaded:

![image](https://cloud.githubusercontent.com/assets/6240170/8789823/69e7d48c-2f14-11e5-924a-2a444db17c66.png)

If I then manually go to "Load from url.." and put in the same accepted_hits.bam url it does load. 

Not to overload this Issue, but I think it might be some problem not tied to the maxPanelHeight command as I've been having a number of other issues with both the batch and port interfaces ignoring commands on both MacOSX and Linux. Hopefully there are other things I can do to troubleshoot other than modifying the source code..

**Comment by npatel22526** [comment] 2016-01-27 17:07
Hi, 

Just came across with the issue. Add space after max and it will resolve the issue. The documentation have it wrong. Instead of "maxPanelHeight 2000" --> "max PanelHeight 2000"

Thanks, 
Nick

**Comment by jrobinso** [comment] 2016-01-27 17:39
That's a little bizzare,  the actual code that checks for this command is  

else if (cmd.equalsIgnoreCase("maxpanelheight") && param1 != null) {
                    return setMaxPanelHeight(param1);

Do you have this problem only when running batch from the command line?  By that I mean does the script work as expected if ran from the "tools" menu of the GUI?

**Comment by npatel22526** [comment] 2016-01-27 17:43
I tried the batch script with GUI only IGV_2.3.68.  With GUI, I needed to add space after "max". I haven't really tried it with command line.
Pardon me I should have clarify that earlier. 

Thank, 
Nick

**Comment by jrobinso** [comment] 2016-01-27 17:52
OK,  I have a note on my long to-do to try and figure this out.

**Comment by jrobinso** [comment] 2016-03-08 20:53
I investigated this.  For me,  maxPanelHeight 2000  works,  max PanelHeight 2000 does not.  This is consistent with the code.  So I'm closing this in the absence of any problem I can reproduce.

**Comment by birndle** [comment] 2016-03-15 13:34
Thank you for your response.

**Comment by astulaaa** [comment] 2021-02-08 07:35
Surprisingly, I get the same issue running different versions of IGV: 2.3.71, 2.8.13, even 2.3.73 which was reported to have a bug fix for this problem. Is there any way to go around it? Is it somehow linked to me loading 4 bam files at once? Or xmanager version? maxPanelHeight does not work no matter what size is denoted. batch is as follows:  
genome hg38
preference SAM.SHOW_ALL_BASES true
preference SAM.DOWNSAMPLE_READS false
maxPanelHeight 2000
snapshotDirectory /Workspace/709.final.bam,/Workspace/708.final.bam,/Workspace/707.final.bam,/Workspace/706.final.bam
goto chr17:31117722-31117622
sort position chr17:31117672
sort base 
snapshot new02080.png 
exit

**Comment by jrobinso** [comment] 2021-02-08 22:30
Did you try the latest release (2.9.0)?

**Comment by jrobinso** [comment] 2021-02-09 04:52
Also, the "snapshotDirectory" command should point to a single directory where all snapshot images will be stored, not a comma delimited list.

**Comment by astulaaa** [comment] 2021-02-10 02:49
Thanks for quick reply, 
With 2.9.0 release I'm getting "WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop" How serious are these warnings? Can't find a quick workaround. 
For snapshot directory, I haven't copied the previous script well, the snapshot directory is denoted properly there, corrected script below.
Even with this warning maxPanelHeight seems to work. However now I'm experiencing 1) large empty space after the last read in each sample. I thought I can define number of reads that will be shown with preference SAM.MAX_LEVELS 30 but the output image does not reflect that. Is it incorrect option? 2) in the IGV version 2.3.71 there were 2 vertical lines in the center denoting the position of interest. How can I enable that on IGV 2.9.0?

genome hg38
preference SAM.SHOW_ALL_BASES true
preference SAM.DOWNSAMPLE_READS false
maxPanelHeight 2000
preference SAM.MAX_LEVELS       30
snapshotDirectory /Workspace/Analysis
load /Workspace/709.final.bam,/Workspace/708.final.bam,/Workspace/707.final.bam,/Workspace/706.final.bam
goto chr17:31117722-31117622
sort position chr17:31117672
sort base
snapshot new02080.png
exit

Thanks

**Comment by jrobinso** [comment] 2021-02-10 04:46
Those are Java warnings, not IGV warnings, you can ignore them.

I don't know what you mean by "large empty space",  a screenshot might help.    RE "MAX_LEVELS 30",  that is one parameter controlling downsampling,  you can read about it here, look in the Downsampling section.   "MAX_LEVELS" is "read count" in the doc, the name is historicalhttp://software.broadinstitute.org/software/igv/AlignmentData

The center line is controlled by user preferences, you can set that manually in the UI or with the "preference" command, 
 the key is SAM.SHOW_CENTER_LINE.

```
preference SAM.SHOW_CENTER_LINE true
```

**Comment by astulaaa** [comment] 2021-02-10 06:50
The regions I visualize are of low coverage.  So the window for each sample is half empty even when the "preference SAM.DOWNSAMPLE_READS false" . I would like to set the number of reads to be shown in the screenshot. I mark with red brackets what I regarded as empty space. Basically, I want this space without reads not shown, which would make my data in the image more compact. Is it possible to set it like that?
![image](https://user-images.githubusercontent.com/44764141/107475158-06ab2a00-6bb7-11eb-8e20-9e7ecac3888e.png)

**Comment by jrobinso** [comment] 2021-02-10 16:35
If you view those same BAM files at the location through the UI do you see scrollbars?  There are probably reads just out of view that are occupying that space.  You can see some of them intruding from the right.   There is nothing to be done about this.  Why do you not just set the maxPanelSize to bet the amount of space needed for the number of rows you want to see?

**Comment by elcortegano** [comment] 2021-04-14 19:32
I got the same error with versions 2.9.2 and 2.9.4.

Setting maxPanelHeight 2000 won't fix it.

Script looks like: 
```

new
load session.xml
maxPanelHeight 2000
snapshotDirectory snapshot/snm/
goto chromosome_01:1207704-1207804
sort base
collapse
snapshot
goto chromosome_02:382713-382813
...
```
Any ideas how this could be fixed? Thank you

**Comment by jrobinso** [comment] 2021-04-14 20:22
"Exact error" is not helpful on a thread that is 5 years old.   Could you describe your problem, and include a screenshot?

**Comment by elcortegano** [comment] 2021-04-14 21:31
I am running IGV 2.9.4 in batch mode on a Ubuntu 20.04 machine with:

    xvfb-run  --auto-servernum igv.sh -b  script.bat

Where the file `script.bat` looks like in the previous post, only that there will be many `goto` commands followed by sort, collapse, and snapshot instructions. As shown in the script, `maxPanelHeight` is set to a size recommended in this thread. However, when there are many reads at a region, the snapshot does not cover them all. Example below:

![chromosome_06_1,001,969_1,002,069](https://user-images.githubusercontent.com/57492899/114781690-eb07ff80-9d70-11eb-8440-247b4d9356d9.png)

**Comment by jrobinso** [comment] 2021-04-15 02:05
OK thanks, will investigate but I'm traveling at the moment.   If no word  in a week ping this issue again.   I don't use "xvfb",  unsure if that is a factor or not.

**Comment by elcortegano** [comment] 2021-04-21 16:01
The problem persist when calling the batch script directly with IGV, e.g.:

    /opt/IGV_Linux_2.9.4/igv.sh  -b script.bat

So it's probably unrelated to `xvfb`.

**Comment by jrobinso** [comment] 2021-04-24 04:26
I cannot reproduce this behavior,  please try the script below and post the resulting png (its public data).    I am attaching the png produced on my Mac. 

```
genome hg19
load https://1000genomes.s3.amazonaws.com/phase3/data/HG01879/exome_alignment/HG01879.mapped.ILLUMINA.bwa.ACB.exome.20120522.bam
maxPanelHeight 2000
goto myc
snapshot
```

![chr8_128,745,680_128,757,197](https://user-images.githubusercontent.com/933148/115947135-7d4b8a00-a47a-11eb-9e70-4d9f0735411e.png)

**Comment by jrobinso** [comment] 2021-04-30 17:05
@elcortegano Did you try the script I posted above?  I need something reproducible, with public or otherwise accessible data, to make nay progress.  First step is to see if you can produce the screenshot above with the script provided.

**Comment by elcortegano** [comment] 2021-04-30 19:23
Hi @jrobinso, sorry for the delay, I had not seen the script above. I post below the screenshot generated. It looks longer than the ones I generate for my data, but I feel it is similarly slightly cut at the bottom.

![chr8_128,745,680_128,757,197](https://user-images.githubusercontent.com/57492899/116744073-bbecc180-a9f1-11eb-85a4-b6790a6b2fb4.png)

**Closed** 2021-05-04 03:43 UTC
