### ISSUE TITLE
unexpecgted error repainintg view

### ISSUE THREAD

**Issue by wjyzidane** [igvteam/igv#1024] opened 2021-09-09 20:47 UTC
Hello,

I am using the IGV(2.11.0) to view a region has about 20-30 reads in bam. When I zoom in, it gives me "unexpected error repainting view" error and no reads at all.

**Comment by jrobinso** [comment] 2021-09-09 21:49
I'll need more information than that to help you.  We could start with the "igv.log" file, located in the igv  folder in your home directory.    If you can reproduce this with public data and share exact steps to reproduce that would be helpful also.

**Comment by wjyzidane** [comment] 2021-09-09 22:08
Hello,

Here is the message from igv.log :
ERROR [2021-09-09T18:06:08,620] [DataPanel.java:174]  Error painting DataPanel
java.lang.NullPointerException: null

and attached are the reads for that region in bam (it gives me the same error):
[blood_chr2_87196925_87619276.bam.zip](https://github.com/igvteam/igv/files/7139975/blood_chr2_87196925_87619276.bam.zip)

**Comment by jrobinso** [comment] 2021-09-09 23:13
I can't reproduce it with that data (see screenshot).   Do you have any custom igv settings?   If so what are they?

If you zip and attach the whole log so I can see the stack trace I will look into this further,  also if you have custom settings or can't recall if you do please zip and attach the "pref.properties" file in the igv folder.

<img width="1382" alt="Screen Shot 2021-09-09 at 4 08 34 PM" src="https://user-images.githubusercontent.com/933148/132774365-9f9d2712-0680-4261-9a9c-5389412dfa04.png">

**Comment by wjyzidane** [comment] 2021-09-10 02:12
Please find them attached. Thanks!
[igv.log.zip](https://github.com/igvteam/igv/files/7140790/igv.log.zip)
[prefs.properties.zip](https://github.com/igvteam/igv/files/7140791/prefs.properties.zip)

**Comment by jrobinso** [comment] 2021-09-10 18:20
I just pushed a change that should fix this, based on your log file.   I can't be sure since I still can't reproduce it, and you have not provided me with steps to reproduce.   The fix will be in the next release, probably early next week.

BTW your log indicates you are viewing this data in bisulfite mode, but the data does not appear to be from bisulfite sequencing.   This should not cause an error, but is unusual.

**Closed** 2021-09-10 18:20 UTC
