### ISSUE TITLE
Modified & saved coverage/junction tracks reset when reloads

### ISSUE THREAD

**Issue by hisplan** [igvteam/igv#766] opened 2020-03-03 11:34 UTC
Version: IGV 2.8.0

How to reproduce:

1. Load BAM file which automatically adds coverage track (and junctions track if enabled).
1. Remove junction track.
1. Update coverage track name to something else (e.g. `my-sample.bam coverage` to `my-sample coverage`)
1. Save the session.
1. Exit out from IGV.
1. Open IGV.
1. Load the saved session.
1. Junction tracks reloads (even though removed). The coverage track name resets (even though modified).

**Comment by jrobinso** [comment] 2020-03-04 18:08
Hi, I found the issue with coverage track name, but can't reproduce the problem with the junction track.

**Comment by hisplan** [comment] 2020-03-04 20:07
Looks like "hide junction track" vs. "remove track" behave differently.

Maybe, `visible` attribute in the session XML resets to `true` during the loading??

**Comment by jrobinso** [comment] 2020-03-04 21:43
Oh yes that's possible.   Remove and hide are different functions, so step
2 should be "hide junction track"?

**Comment by jrobinso** [comment] 2020-03-04 22:00
Fixed with commit c57f29dafd1ec3a38ef0bbaef63d13f372bae56a

**Closed by jrobinso** 2020-03-04 22:00 UTC
