### ISSUE TITLE
Could not open certain file types from AWS S3 bucket.

### ISSUE THREAD

**Issue by tshuklanygc** [igvteam/igv#907] opened 2021-02-08 18:14 UTC
Could not open certain file types (e.g. session files, or bw bigiwg files) from AWS S3 bucket. It throws error that 'No such file or directory'

I came across an issue with a bigwig file with .bw extension. When I try to open the file I get - Error loading s3://..... (The filename, directory name or volume label syntax is incorrect). If I download the file locally and try to open it there are no issues. Also, other files like bam open as expected from the same s3 location."

Note - We are using Amazon IGV backend setup as documented on umccr.org

**Comment by jrobinso** [comment] 2021-02-08 22:28
Only a few file types are supported,  bigwig is not one of them.

**Comment by tshuklanygc** [comment] 2021-02-08 23:07
> Only a few file types are supported, bigwig is not one of them.

Thanks for the quick reply. I guess when you say only a few file types are supported, you mean only for aws because I see it works for gcp. Could we expect the support to expand in near future?

**Comment by jrobinso** [comment] 2021-02-09 04:48
@tshuklanygc I should be more precise, only a few file types support s3:// URLs (these are listed at the UMCCR site).    Support for public S3 files are supported for all file types with their https:// URLs.   In fact all of our hosted data is on S3.   

UMCCR contributed the current implementation,  bigwig and other files types are not a priority for them.   I do plan to reimplement this in a more general way but there is no timeline,  I have a lot of competing priorities for my time so I don't want to set an expectation on this one.

**Comment by jrobinso** [comment] 2021-02-09 04:50
Closing as this is a duplicate of #856.

**Closed by jrobinso** 2021-02-09 04:50 UTC
