### ISSUE TITLE
Load from S3 buckets dialog not working

### ISSUE THREAD

**Issue by awilcz** [igvteam/igv#861] opened 2020-11-02 13:52 UTC
Hi, we've got an S3 bucket set up as directed by: https://umccr.org/blog/igv-amazon-backend-setup/. There's no problem signing in or subsequent loading of files from URL (aside from bigwig files, as discussed elsewhere) but it is impossible to load the files directly from the Amazon > Load from S3 bucket dialog box, though all the files are readily visible there.
The error in IGV is : Unexpected error: null. See igv.log for more details

And the  relevant snippet of the igv.log is: 

INFO [2020-11-02T13:43:14,174] [MessageUtils.java:76]  <html>Unexpected error: null.<br>See igv.log for more details
ERROR [2020-11-02T13:43:14,174] [LongRunningTask.java:75]  Exception running task
java.lang.NullPointerException: null
	at org.broad.igv.util.AmazonUtils.isObjectAccessible(AmazonUtils.java:250) ~[igv.jar:?]
	at org.broad.igv.aws.S3LoadDialog.lambda$loadButtonActionPerformed$0(S3LoadDialog.java:106) ~[igv.jar:?]
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72) [igv.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]

**Comment by jrobinso** [comment] 2020-11-02 19:27
I believe this is fixed in version, which is not released pending some additional testing on Windows 10.     If you could try 2.8.11 and give us feedback that would be helpful.   Here are direct links to the installers

Windows: https://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_Win_2.8.11-WithJava-installer.exe
Mac: https://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_MacApp_2.8.11_WithJava.zip
Linux: https://data.broadinstitute.org/igv/projects/downloads/2.8/IGV_Linux_2.8.10_WithJava.zip

**Comment by brainstorm** [comment] 2020-11-03 01:00
@jrobinso The last link points to 2.8.10, it's what you intended?

**Comment by jrobinso** [comment] 2020-11-03 03:55
@brainstorm Thanks, no it was not, corrected.

**Comment by awilcz** [comment] 2020-11-03 10:57
Hi there, it does try to load the files form the dialog, so that's great, but errors with the index: 
Error loading s3://........(my file name).vcf: An index is required, but none found., 

The index file is present and all can be loaded no problem from URLs. I tried a BAM and had the same issue - doesn't work whether I only select the BAM or both the BAM and BAI...

**Comment by brainstorm** [comment] 2020-11-04 06:17
@awilcz IGV looks for any of the `.bam.bai` and other combinations by convention, you can check here:

https://github.com/igvteam/igv/blob/master/src/main/java/org/broad/igv/sam/reader/BAMReader.java#L236

But I cannot reproduce your issue with this 2.8.11 IGV pre-release Jim pointed above... can you paste your Cognito policy here? I suspect there's something wrong with the AWS permissions for your bucket(s).

**Comment by brainstorm** [comment] 2020-11-06 00:10
@awilcz Alternatively, feel free to reach me directly over brainstorm at nopcode dot org and we can have a look at it.

**Comment by awilcz** [comment] 2020-11-07 18:35
OK, the bam loading works well with bam.bai but from the link you posted, shouldn't it also be able to see .bai? 
VCF doesn't load from vcf.idx. What extension in the index will it accept?

**Comment by brainstorm** [comment] 2020-11-08 10:02
We regularly use `.vcf.gz` and its corresponding `.vcf.gz.tbi`, can you try with that combination?

**Comment by brainstorm** [comment] 2020-11-08 22:56
> OK, the bam loading works well with bam.bai but from the link you posted, shouldn't it also be able to see .bai?

Can you paste here the full paths to those files (and extensions) that triggered your initial issue? Could be useful for testing.

**Comment by jrobinso** [comment] 2020-11-09 06:37
I think this might be related to #856.    @brainstorm can we say that this works, or at least has been tested,  only for BAM/CRAM,  tabix indexed VCF  (vcf.gz / vcf.gz.tbi),  and non-indexed feature formats (bed, etc)?   I don't recall the details but that's my recollection.

In the next round of IGV development I am going to tackle #856 by moving the fetching of signed URLs to the http utils level.   The reasonable expectation for this feature is that it should work for all supported file types.   I just finished a big igv.js release and plan to start on the next batch of IGV desktop work, which includes #856 this week.

**Comment by brainstorm** [comment] 2020-11-09 07:01
That's right Jim, this morning I was about to trace this one but got sidetracked, glad to see you'll get into this one for good :)

/cc @reisingerf

**Comment by jrobinso** [comment] 2020-11-09 17:08
@brainstorm @reisingerf I updated the README, but you might want to update the blogpost since many will find it directly via a web search.

**Comment by brainstorm** [comment] 2020-11-09 19:38
Noted and published on the blog: https://github.com/umccr-svc/site/commit/543f6054f27ad25f188ab9fc70de051ab62eaf7e

If there are no objections from @awilcz, I would close those issue in favor of #856 

/cc @ohofmann

**Comment by jrobinso** [comment] 2020-11-10 06:06
Closing as this is a duplicate of #856

**Closed by jrobinso** 2020-11-10 06:06 UTC
