### ISSUE TITLE
Add support for Google Requester Pays buckets billing project

### ISSUE THREAD

**Issue by mbookman** [igvteam/igv#489] opened 2017-11-21 21:35 UTC
As was discussed in the IGV web issue:

https://github.com/igvteam/igv.js/issues/393

Google Cloud has added [Requester Pays](https://cloud.google.com/storage/docs/requester-pays) access to Cloud Storage buckets.

For this to work, fetches from Cloud Storage for a requester pays bucket need to include a project ID to bill to. Please add a way for end-users to specify this billing project ID.

**Comment by jrobinso** [comment] 2017-12-14 17:45
How would this work?  Would they specify it once globally for all GCS resources?

**Comment by mbookman** [comment] 2017-12-14 19:15
It is reasonable to set it up as a per-user IGV setting.
Then the question would be - when to set userProject flag in the API?

The way that the GCS API works is that it is fine to always send the userProject. If the bucket is not requester pays, then the option is ignored. So that is an option - always send it if a user has the setting.

On the other hand, people might not want their Cloud Project sent for all GCS requests, so you could start without including it, catch the error and retry with the userProject. Here's the error:

    BadRequestException: 400 Bucket is requester pays bucket but no user project provided.

Not sure how straight-forward that would be to implement (or how many places in code would require the handler).

Given that there is no support for requester pays at the moment, then having a global setting that is always sent when specified would satisfy a minimum need for users.

Ideally, I think I would want to be able to store the project as a setting on a per-bucket basis. There is a good chance that any given user would only interact with a very small number of requester pays buckets.

FWIW, in the Google Cloud Console when you view a Requester Pays bucket, you'll get a message:

    Select a project to bill
    All data charges for the bucket <blah> will be billed to the project selected here. [Learn more]

    [ Select a project ] <- dropdown
 
    [ ] I understand that this project will be billed for this bucket's data charges.

The selected project is then cached and used for subsequent requests on that bucket.

**Comment by francois-a** [comment] 2018-06-19 23:51
It would be very useful to be able to access requester pays buckets. Are there any plans to add support for this sometime soon?

**Comment by jrobinso** [comment] 2018-06-29 19:02
@francois-a I'm working on it now,  waiting for input from @mbookman.   It should be available soon.

**Comment by jrobinso** [comment] 2018-10-25 21:02
Closing this issue,  I attempted to add support, and it should work, but I don't have any way to test it.

**Closed by jrobinso** 2018-10-25 21:02 UTC

**Comment by mwalker174** [comment] 2019-12-03 16:10
Hi,

I am attempting to open a CRAM in a requester pays bucket. I set the project at Google -> Enter Project ID .. in the toolbar, but receive this error message trying to open from a URL:

```
Error loading https://www.googleapis.com/storage/v1/b/fc-56ac46ea-efc4-4683-b6d5-6d95bed41c5e/o/CCDG_13607%2FProject_CCDG_13607_B01_GRM_WGS.cram.2019-02-06%2FSample_HG00114%2Fanalysis%2FHG00114.final.cram?alt=media: An error occurred while accessing: https://www.googleapis.com/storage/v1/b/fc-56ac46ea-efc4-4683-b6d5-6d95bed41c5e/o/CCDG_13607%2FProject_CCDG_13607_B01_GRM_WGS.cram.2019-02-06%2FSample_HG00114%2Fanalysis%2FHG00114.final.cram?alt=media Error loading BAM file: org.broad.igv.exceptions.HttpResponseException: Bad Request Bucket is requester pays bucket but no user project provided.
```

**Comment by jrobinso** [comment] 2019-12-05 21:18
Hi,  I cant reproduce this error.  I'm somewhat hampered as I don't have a billable google account to test with, but in a simulation with public gs:// bam files the userProject parameter is added as expected. 

Could you provide your igv.log file, its located in an igv folder under your home directory.  If you don't want to post it here you can send it by email to  igv-team (at) broadinstitute.org.

**Comment by mwalker174** [comment] 2020-07-27 18:13
@jrobinso Sorry I had forgotten about this but am running into the same issue again. I've attached my log after starting IGV, logging in with Google->Log in, entering the project under Google->Enter project ID, and attempting to load with File->Load From URL.
[igv.log](https://github.com/igvteam/igv/files/4983756/igv.log)
(redacted oauth url)

**Comment by jrobinso** [comment] 2020-07-27 20:43
@mwalker174 I can't reproduce it, but I have no way to test google pay buckets.  I did verify that the parameter  "userProject=<project id> is added to the request.   You might try adding that manually to the URL to see if it makes a different, in other words add  ?userProject=yourProject  to the URL you past into "load from url".

**Comment by tmm211** [comment] 2020-07-27 21:39
I am running into the very same issue on 2.8.7. Adding userProject on the end doesn't seem to work :/

**Comment by jrobinso** [comment] 2020-07-27 21:50
@mwalker174 @tmm211 If either of you have the ability to setup a test case I can use I will look further into it,  I've done all I can do without the ability to test.  If that's possible you can communicate privately through the igv-team emai   (igv-team (at) broadinstitute.org).

**Comment by bw2** [comment] 2021-02-22 18:47
I'm still having trouble with this in the newest version (v2.9.2) from https://software.broadinstitute.org/software/igv/download
I can log in & set a project id in the Google menu, but get a UI error message:
```
Error loading BAM file: org.broad.igv.exceptions.HttpResponseException: Bad Request Bucket is requester pays bucket but no user project provided.
```
and the IGV output contains
```
INFO [2021-02-22T13:25:38,453]  [TrackLoader.java:122] [pool-3-thread-2]  Loading resource, path https://www.googleapis.com/storage/v1/b/.._PM_1.cram?alt=media
INFO [2021-02-22T13:25:38,799]  [MessageUtils.java:76] [pool-3-thread-2]  <html>Bucket is requester pays bucket but no user project provided.<br>Use Google menu to set project.
```
At the same time, running gsutil -u <project> ls gs://..PM_1.cram does work.

Jim, I'll  email you the full bucket path to see if you can access it.
