### ISSUE TITLE
View as pairs error

### ISSUE THREAD

**Issue by jandrewrfarrell** [igvteam/igv#896] opened 2021-01-28 18:32 UTC
on the Linux version of IGV, when ever I right click on a cram track and select "view as pairs" IGV freezes and never shows the pairs.  Often I need to restart IGV to continue.  Below is the error printed on the command line

ERROR [2021-01-28T11:28:35,983]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NullPointerException: null
	at org.broad.igv.sam.AlignmentRenderer.getAlignmentColor(AlignmentRenderer.java:1264) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentRenderer.renderAlignments(AlignmentRenderer.java:313) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentTrack.renderAlignments(AlignmentTrack.java:549) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentTrack.render(AlignmentTrack.java:444) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanelPainter.draw(DataPanelPainter.java:229) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanelPainter.paintFrame(DataPanelPainter.java:165) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanelPainter.paint(DataPanelPainter.java:102) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanel.paintComponent(DataPanel.java:170) ~[igv.jar:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at org.broad.igv.ui.panel.DataPanelContainer.paintChildren(DataPanelContainer.java:154) ~[igv.jar:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JViewport.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JLayeredPane.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintToOffscreen(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source) ~[?:?]
	at javax.swing.BufferStrategyPaintManager.paint(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent._paintImmediately(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintImmediately(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$4.run(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source) ~[?:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]

**Comment by jrobinso** [comment] 2021-01-30 00:00
What version of IGV are you using?  This looks like a bug that was fixed some time ago.

**Comment by jandrewrfarrell** [comment] 2021-01-30 11:42
this is with IGV_Linux_2.8.13, I just did a fresh download to check and I still got the same error.  Here is the full out too , I removed 126295 lines 
that said some form of "INFO [2021-01-30T04:30:49,807]  [AlignmentDataManager.java:339] [pool-2-thread-4]  Already loading: chr1:99999979-100000019"

nohup: ignoring input
echo Using bundled JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
WARN [2021-01-30T04:29:52,743]  [Globals.java:134] [main]  Development mode is enabled
INFO [2021-01-30T04:29:52,807]  [DirectoryManager.java:179] [main]  IGV Directory: /uufs/chpc.utah.edu/common/HIPAA/u0991464/igv
INFO [2021-01-30T04:29:55,640]  [Main.java:205] [AWT-EventQueue-0]  Startup  IGV Version 2.8.13 11/20/2020 12:50 AM
INFO [2021-01-30T04:29:55,674]  [Main.java:206] [AWT-EventQueue-0]  Java 11.0.8 (build 11.0.8+10) 2020-07-14
INFO [2021-01-30T04:29:55,676]  [Main.java:209] [AWT-EventQueue-0]  Java Vendor: AdoptOpenJDK https://adoptopenjdk.net/
INFO [2021-01-30T04:29:55,677]  [Main.java:211] [AWT-EventQueue-0]  JVM: OpenJDK 64-Bit Server VM AdoptOpenJDK   
INFO [2021-01-30T04:29:55,678]  [DirectoryManager.java:84] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2021-01-30T04:29:55,995]  [Main.java:214] [AWT-EventQueue-0]  Default User Directory: /uufs/chpc.utah.edu/common/HIPAA/u0991464
INFO [2021-01-30T04:29:55,998]  [Main.java:215] [AWT-EventQueue-0]  OS: Linux 3.10.0-957.27.2.el7.x86_64 amd64
INFO [2021-01-30T04:29:59,889]  [GenomeManager.java:183] [pool-3-thread-1]  Loading genome: /uufs/chpc.utah.edu/common/HIPAA/u0991464/igv/genomes/hg38.genome
INFO [2021-01-30T04:30:11,568]  [GenomeManager.java:224] [pool-3-thread-1]  Genome loaded.  id= hg38
ERROR [2021-01-30T04:30:11,583]  [CommandListener.java:141] [Thread-4]  java.net.BindException: Address already in use (Bind failed)
Gtk-Message: 04:30:21.619: GtkDialog mapped without a transient parent. This is discouraged.
INFO [2021-01-30T04:30:35,090]  [IGV.java:1333] [pool-3-thread-2]  Loading 3 resources.
INFO [2021-01-30T04:30:35,106]  [TrackLoader.java:122] [pool-3-thread-2]  Loading resource, path /scratch/ucgd/lustre-work/u0991464/Projects/Neoseq/IRB_00125940/A1099-1024-NEO-Congenital_diaphragmatic_hernia/UCGD/GRCh38/Analysis/CRAMs/1024-01.cram
INFO [2021-01-30T04:30:37,179]  [TrackLoader.java:122] [pool-3-thread-2]  Loading resource, path /scratch/ucgd/lustre-work/u0991464/Projects/Neoseq/IRB_00125940/A1099-1024-NEO-Congenital_diaphragmatic_hernia/UCGD/GRCh38/Analysis/CRAMs/1024-02.cram
INFO [2021-01-30T04:30:37,201]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:40,129]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:40,167]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:40,193]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:40,220]  [TrackLoader.java:122] [pool-3-thread-2]  Loading resource, path /scratch/ucgd/lustre-work/u0991464/Projects/Neoseq/IRB_00125940/A1099-1024-NEO-Congenital_diaphragmatic_hernia/UCGD/GRCh38/Analysis/CRAMs/1024-03.cram
INFO [2021-01-30T04:30:40,225]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:40,229]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:40,238]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:41,469]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:41,474]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:41,493]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:41,496]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:41,499]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:41,518]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:41,521]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:41,523]  [AlignmentTrack.java:479] [AWT-EventQueue-0]  No alignment interval for All
INFO [2021-01-30T04:30:48,927]  [HttpUtils.java:961] [pool-2-thread-2]  Range-byte request succeeded
A00576:233:HW7T5DRXX:2:1115:15790:5196:CCCTT+GGAAA	-1852	3557	5409
A00576:233:HW7T5DRXX:1:1231:29324:19116:GTACA+ATCTC	-1593	3816	5409
A00576:233:HW7T5DRXX:1:1231:30129:17096:GTACA+ATCTC	-1593	3816	5409
A00576:233:HW7T5DRXX:1:1231:30092:17065:GTACA+ATCTC	-1593	3816	5409
A00576:233:HW7T5DRXX:2:1214:21793:20259:ATGGA+TATCT	-1037	4372	5409
ERROR [2021-01-30T04:31:13,985]  [DefaultExceptionHandler.java:49] [AWT-EventQueue-0]  Unhandled exception
java.lang.NullPointerException: null
	at org.broad.igv.sam.AlignmentRenderer.getAlignmentColor(AlignmentRenderer.java:1264) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentRenderer.renderAlignments(AlignmentRenderer.java:313) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentTrack.renderAlignments(AlignmentTrack.java:549) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentTrack.render(AlignmentTrack.java:444) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanelPainter.draw(DataPanelPainter.java:229) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanelPainter.paintFrame(DataPanelPainter.java:165) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanelPainter.paint(DataPanelPainter.java:102) ~[igv.jar:?]
	at org.broad.igv.ui.panel.DataPanel.paintComponent(DataPanel.java:170) ~[igv.jar:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at org.broad.igv.ui.panel.DataPanelContainer.paintChildren(DataPanelContainer.java:154) ~[igv.jar:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JViewport.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JLayeredPane.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintChildren(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintToOffscreen(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source) ~[?:?]
	at javax.swing.BufferStrategyPaintManager.paint(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager.paint(Unknown Source) ~[?:?]
	at javax.swing.JComponent._paintImmediately(Unknown Source) ~[?:?]
	at javax.swing.JComponent.paintImmediately(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$4.run(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source) ~[?:?]
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source) ~[?:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.awt.EventQueue$4.run(Unknown Source) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:?]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:?]
=====================================
Andrew Farrell PhD               
Director of Research and Science          
Department of Human Genetics              
USTAR Center for Genetic Discovery   
Eccles Institute of Human Genetics   
University of Utah School of Medicine​
15 North 2030 East, Room 7140         
Salt Lake City, UT 84112-5330        
Email: JAndrewRFarrell@gmail.com         
http://marthlab.org/
=====================================

**Comment by jrobinso** [comment] 2021-01-31 03:56
Thank you, that stack trace is helpful.   I think this has been fixed but not released, the release will be early next week (2.9).  In the meantime the nightly snapshot has the fix.  Also, if "insert size" coloring is not important you can change the coloring option to "None" to work around this from the "Color by" option in the alignments view.

BTW this error can only occur when the alignment is "paired" but the mate chromosome for one of the alignments in view is "null" from the htsjdk.  Looking at the htsjdk code its clear that this is an unexpected condition.   So something about this CRAM file wrt treatement of read mates is not expected by the htsjdk code.   If its possible to share one of these CRAMs I'll look into it further and perhaps raise in issue in the htsjdk repository.   The specific bug referenced here will be solved in IGV 2.9 with a null check, but there could be further issues with IGV or other tools.

If it's not possible to share one of these CRAMs perhaps just the alignment details of one or two alignments would be informative.  You can get these details by right-clicking an alignment and selecting "paste read details to clipboard".

**Comment by jrobinso** [comment] 2021-02-03 05:18
I think this is fixed with release 2.9.0.   I don't actually have a CRAM to reproduce the problem with so I can't be sure, if its not please reopen.

**Closed by jrobinso** 2021-02-03 05:18 UTC
