### ISSUE TITLE
IGV open session

### ISSUE THREAD

**Issue by diego-rt** [igvteam/igv#1272] opened 2022-12-19 22:59 UTC
Hello,

When opening a saved session including BAM files indexed using a CSI index (as opposed to bai), IGV only searched for the .bai indexes (and fails) and queries the user to point towards the location of the index. However, even after pointing to the right location this process fails and I'm not sure why. We are working with the giant axolotl genome which has always managed to trigger pretty weird bugs (including some in IGV that you have patched before). 

Overall I would say my experience with IGV with this genome is perfectly normal when working with BED and BW files, but as soon as you get into BAM files or sessions, we get into problems.

I'm attaching the log of the "Open session" issue:

[igv0.log](https://github.com/igvteam/igv/files/10263345/igv0.log)

Thanks a lot for looking into it!

**Comment by diego-rt** [comment] 2022-12-20 01:07
2.15.4 on macOS Ventura

**Comment by jrobinso** [comment] 2022-12-20 01:08
I'm not able to reproduce the problem.   Could you zip and attach your session xml file, that might provide a clue.

**Comment by diego-rt** [comment] 2022-12-20 01:11
Sure, thanks for looking into it! I will upload them tomorrow morning as soon as I'm in my computer.

**Comment by jrobinso** [comment] 2023-01-21 00:16
Closing, reopen if you can provide files that reproduce the problem, along with a log file.

**Closed by jrobinso** 2023-01-21 00:16 UTC

**Comment by diego-rt** [comment] 2023-03-01 13:06
Sorry for the delay. Here are the log files and the session xml (renamed to .txt because GitHub otherwise doesnt let me upload it).

[igv1.log](https://github.com/igvteam/igv/files/10861278/igv1.log)
[Session.xml.txt](https://github.com/igvteam/igv/files/10861284/Session.xml.txt)

**Comment by diego-rt** [comment] 2023-03-02 23:31
Oh and one more thing @jrobinso . With this huge genome (32Gbp), whenever I zoom in to a level where the bases are visible in the bottom track, it becomes unresponsive and super slow but eventually recovers. It is a similar behaviour to the bug that involved slowing down in coordinates past 2Gbp that you fixed already a few months ago. Perhaps it is a similar issue with an out of bounds variable?
