### ISSUE TITLE
Support for CSI BAM Index

### ISSUE THREAD

**Issue by nathanhaigh** [igvteam/igv#96] opened 2014-08-20 04:59 UTC
Samtools 1.0 was released recently, which now uses the new htslib (https://github.com/samtools/htslib). htslib is able to index BAM files containing reference sequences above the 2<sup>29</sup>-1bp limit imposed by the old BAI index.

This is an important step for those of us dealing with chromosomes longer than ~537 Mbases since the new CSI index limits aligns with the existing reference sequience length limit of 2<sup>31</sup>-1bp (or ~2.15 Gbases) defined in the SAM spec.

I'd like to request that IGV be able to support this new BAM index format ASAP.

**Comment by travc** [comment] 2016-06-18 08:15
Any progress on this?  Are `CSI` indexes supposed to work now?

I've tried it out with 2.3.77 and it seems to take a `CSI` index, but fails to show any reads.
Of course, the failure could be something else entirely... network issues are possible since I'm loading from URL.

**Comment by jrobinso** [comment] 2016-06-19 00:06
Hi,

CRAM support is only available in the "snapshot" build or the master 
branch.  It should work with .crai and .bai indeces.

Sorry I'm not well versed on cram lingo, what is a "CSI" index?

Jim

**Comment by jrobinso** [comment] 2016-06-19 00:10
Apologies for the completely off topic CRAM comment, since deleted.   Do you have a test file available with a CSI index?

**Comment by jrobinso** [comment] 2016-06-19 00:15
I just checked the htsjdk,  which IGV uses,  and it appears that it does not support CSI indexes.  There is an open git issue no this topic here:  https://github.com/samtools/htsjdk/issues/447.    IGV will support this when and if htsjdk supports this, or someone submits a pull request with some alternative solution.

**Comment by travc** [comment] 2016-06-20 05:29
Could I suggest catching the problem early and outputting a prominent error?

The latest binary distro (2.3.77) just give a "Error fetching content length" error to the console/terminal when one gives it a `CSI` index.  Everything looks normal except no reads are shown.

Invalid `BAI` indexes (because one or more of the contigs is too long) aren't any more obvious.  Those may be harder to detect though.

**Comment by travc** [comment] 2016-06-20 21:00
Since the problem seems to be based on one of the ref scaffolds being too big, a small sample is tricky.

I just emailed a link to igv-team. Subject line is "IGV issue #96: Test data"  
It isn't human data, so no HIPAA concerns, but I'd rather not just post it openly.

**Comment by jrobinso** [comment] 2016-06-24 05:01
I just pushed a change that will fail immediately if any sequence in the bam is > the bai limit.  I'm going to close this issue as IGV is really dependent on the htsjdk.  Further comments and advocacy for CSI support should be directed to https://github.com/samtools/htsjdk/issues/447.

**Closed by jrobinso** 2016-06-24 05:01 UTC

**Comment by jrobinso** [comment] 2019-01-26 00:05
At long last CSI indeces are supported by the htsjdk.   I've implemented support in IGV,  it will be released this weekend as 2.4.17.

**Comment by sagnikbanerjee15** [comment] 2019-02-14 20:43
Hello,

Thank you for updating IGV with the latest version of htsjdk. I downloaded the latest IGV and was attempting to view alignments. I work with barley which has chromosomes greater than 2^29-1. I was able to load the genome and also view the gene annotations which was provided to IGV in gff3 format. As for the alignments, I generated a csi index. I loaded the bamfile and entered a coordinate I wished to view. I got the following error - "Error encountered querying alignments: htsjdk.samtools.SAMException: Unexpected number of metadata chunks 3". Please see the attached image.

Thank you.
![image](https://user-images.githubusercontent.com/23457977/52816456-e4817e80-3066-11e9-9ec2-e3dfe5d3489e.png)

**Comment by jrobinso** [comment] 2019-02-14 21:15
Hi,   this indicates a problem with the index itself,  or an error in the
code that reads it (https://github.com/samtools/htsjdk).     Are you able
to view this region with samtools?

This bug could be reported @ the htsjdk github but they will probably need
a test case to reproduce it.   Can you make the bam and index available?

**Comment by sagnikbanerjee15** [comment] 2019-02-14 21:22
I can view this region with samtools.
Thanks.

**Comment by jrobinso** [comment] 2019-02-14 21:29
OK, there isn't anything I can do about this in IGV,  I suggest you report it at https://github.com/samtools/htsjdk,  but if you can make the data available I will have a look.

**Comment by jrobinso** [comment] 2019-02-14 21:29
Also, include the "igv.log" file in the igv folder (under user home).

**Comment by Pummyankita** [comment] 2019-02-21 13:07
Hello,
I downloaded the latest IGV and was attempting to view alignments. I work with wheat which has chromosomes greater than 500Mb. I generated a csi index. I loaded the bamfile for the same, but was not able to view anything except the ref. sequence. If any one knows please help.
Thanks
