### ISSUE TITLE
build issue version with 2.15.4

### ISSUE THREAD

**Issue by kbipinkumar** [igvteam/igv#1274] opened 2022-12-21 11:15 UTC
i am getting following error while building igv. 

```
🕙[ 04:41 PM ] ❯ ./gradlew createDist

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
> Exception java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.reflection.ReflectionCache [in thread "Daemon worker"]

* Exception is:
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.runtime.InvokerHelper
        at org.gradle.internal.extensibility.DefaultExtraPropertiesExtension.<init>(DefaultExtraPropertiesExtension.java:29)
        at org.gradle.internal.extensibility.DefaultConvention.<init>(DefaultConvention.java:48)
        at org.gradle.api.internal.plugins.DefaultConvention.<init>(DefaultConvention.java:28)
        at org.gradle.internal.extensibility.ExtensibleDynamicObject.<init>(ExtensibleDynamicObject.java:60)
        at org.gradle.internal.instantiation.MixInExtensibleDynamicObject.<init>(MixInExtensibleDynamicObject.java:34)
        at org.gradle.initialization.DefaultSettings_Decorated.getAsDynamicObject(Unknown Source)
        at org.gradle.initialization.SettingsFactory.createSettings(SettingsFactory.java:58)
        at org.gradle.initialization.ScriptEvaluatingSettingsProcessor.process(ScriptEvaluatingSettingsProcessor.java:60)
        at org.gradle.initialization.PropertiesLoadingSettingsProcessor.process(PropertiesLoadingSettingsProcessor.java:37)
        at org.gradle.initialization.SettingsEvaluatedCallbackFiringSettingsProcessor.process(SettingsEvaluatedCallbackFiringSettingsProcessor.java:34)
        at org.gradle.initialization.RootBuildCacheControllerSettingsProcessor.process(RootBuildCacheControllerSettingsProcessor.java:36)
        at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:50)
        at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.initialization.BuildOperationSettingsProcessor.process(BuildOperationSettingsProcessor.java:47)
        at org.gradle.initialization.DefaultSettingsLoader.findSettingsAndLoadIfAppropriate(DefaultSettingsLoader.java:104)
        at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:45)
        at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
        at org.gradle.internal.composite.CommandLineIncludedBuildSettingsLoader.findAndLoadSettings(CommandLineIncludedBuildSettingsLoader.java:34)
        at org.gradle.internal.composite.ChildBuildRegisteringSettingsLoader.findAndLoadSettings(ChildBuildRegisteringSettingsLoader.java:47)
        at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:35)
        at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:36)
        at org.gradle.initialization.NotifyingSettingsPreparer$LoadBuild.doLoadBuild(NotifyingSettingsPreparer.java:59)
        at org.gradle.initialization.NotifyingSettingsPreparer$LoadBuild.run(NotifyingSettingsPreparer.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
```

**Comment by jrobinso** [comment] 2022-12-21 16:20
What version of java and Gradle are you using?

**Comment by kbipinkumar** [comment] 2022-12-21 16:45
> What version of java and Gradle are you using?

- gradle 7.5.1
-  java-19-openjdk

**Comment by jrobinso** [comment] 2022-12-21 17:01
We build with Java 11, as noted other versions should work but we don't test them.   A little web searching indicates this error might be caused by Java version - Gradle version incompatibility.   According to the Gradle documentation Java 19 would require Gradle 7.6

https://docs.gradle.org/current/userguide/compatibility.html

**Comment by kbipinkumar** [comment] 2022-12-21 17:06
> We build with Java 11, as noted other versions should work but we don't test them. A little web searching indicates this error might be caused by Java version - Gradle version incompatibility. According to the Gradle documentation Java 19 would require Gradle 7.6
> 
> https://docs.gradle.org/current/userguide/compatibility.html

Okay, so for the time being, downgrade the environment seems to be the option

**Comment by davideby** [comment] 2022-12-21 17:09
@kbipinkumar You could try it but you'd need to use `gradle creatDist` instead of `./gradlew createDist` which uses the gradle wrapper and specifies gradle 5.5.1.  You would still need to update your local gradle to support Java 19 from that link @jrobinso sent.

But we can't vouch for the build results there.  It's quite possible that our build.gradle file is not compatible with Gradle 7.6.  The only way to be sure right now is to use Java 11 and the gradle wrapper.

**Comment by jrobinso** [comment] 2022-12-21 17:41
I think but can't be sure there are known instances of IGV builds with Java 17 working out-of-the-box.   We are never going to explicitly support non long-term-support versions such as Java 19 but will be migrating to 17 early next year.

**Comment by jrobinso** [comment] 2023-01-10 22:02
I'm closing this as there's nothing really to do here while we are supporting Java 11.  We will be moving to the next LTS release, Java 17, in the next few months.

**Closed by jrobinso** 2023-01-10 22:02 UTC
