### ISSUE TITLE
Sessions with relative paths won't load again

### ISSUE THREAD

**Issue by flyingicedragon** [igvteam/igv#882] opened 2020-12-30 14:56 UTC
I meet preblem like this issue https://github.com/igvteam/igv/issues/693#issue-495894736.

My IGV version is 2.8.9.

```bash
...
ERROR [2020-12-30T22:48:11,420]  [DataPanel.java:250] [AWT-EventQueue-0]  Error: 
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.lang.NullPointerException
        at org.broad.igv.track.DataSourceTrack.getSummaryScores(DataSourceTrack.java:96) ~[igv.jar:?]
        at org.broad.igv.track.DataTrack.load(DataTrack.java:144) ~[igv.jar:?]
        at org.broad.igv.ui.panel.DataPanel.lambda$load$3(DataPanel.java:222) ~[igv.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
        ... 3 more
ERROR [2020-12-30T22:48:11,424]  [DataPanel.java:250] [pool-2-thread-3]  Error: 
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at org.broad.igv.track.DataSourceTrack.getSummaryScores(DataSourceTrack.java:96) ~[igv.jar:?]
        at org.broad.igv.track.DataTrack.load(DataTrack.java:144) ~[igv.jar:?]
        at org.broad.igv.ui.panel.DataPanel.lambda$load$3(DataPanel.java:222) ~[igv.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
        ... 3 more
ERROR [2020-12-30T22:48:11,443]  [DataPanel.java:250] [pool-2-thread-4]  Error: 
java.util.concurrent.CompletionException: java.lang.NullPointerException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at org.broad.igv.track.DataSourceTrack.getSummaryScores(DataSourceTrack.java:96) ~[igv.jar:?]
        at org.broad.igv.track.DataTrack.load(DataTrack.java:144) ~[igv.jar:?]
        at org.broad.igv.ui.panel.DataPanel.lambda$load$3(DataPanel.java:222) ~[igv.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
        ... 3 more
```

**Comment by jrobinso** [comment] 2020-12-30 19:43
I don't think that's a relative path session error.   The session below works for me.   You might try version 2.8.12,   I think this problem might be fixed there.


```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Session genome="hg18" locus="chr1:1-500" version="8">
    <Resources>
        <Resource path="../bed/test.bed"/>
        <Resource path="../bed/test2.bed"/>
    </Resources>
    <Panel height="944" name="FeaturePanel" width="1967">
        <Track attributeKey="test2.bed" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" colorScale="ContinuousColorScale;0.0;3.0;255,255,255;0,0,178" fontSize="10" height="120" id="/Users/jrobinso/igv-team Dropbox/James Robinson/projects/igv/test/data/bed/test2.bed" name="Test Bed 2" visible="true"/>
        <Track attributeKey="test.bed" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" colorScale="ContinuousColorScale;0.0;5.0;255,255,255;0,0,178" fontSize="10" height="120" id="/Users/jrobinso/igv-team Dropbox/James Robinson/projects/igv/test/data/bed/test.bed" name="Test Bed" visible="true"/>
    </Panel>
    <PanelLayout dividerFractions="0.0062827225130890054"/>
    <HiddenAttributes>
        <Attribute name="DATA FILE"/>
        <Attribute name="DATA TYPE"/>
        <Attribute name="NAME"/>
    </HiddenAttributes>
</Session>
```

**Comment by flyingicedragon** [comment] 2021-01-05 07:36
> I don't think that's a relative path session error. The session below works for me. You might try version 2.8.12, I think this problem might be fixed there.
> 
> ```
> <?xml version="1.0" encoding="UTF-8" standalone="no"?>
> <Session genome="hg18" locus="chr1:1-500" version="8">
>     <Resources>
>         <Resource path="../bed/test.bed"/>
>         <Resource path="../bed/test2.bed"/>
>     </Resources>
>     <Panel height="944" name="FeaturePanel" width="1967">
>         <Track attributeKey="test2.bed" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" colorScale="ContinuousColorScale;0.0;3.0;255,255,255;0,0,178" fontSize="10" height="120" id="/Users/jrobinso/igv-team Dropbox/James Robinson/projects/igv/test/data/bed/test2.bed" name="Test Bed 2" visible="true"/>
>         <Track attributeKey="test.bed" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" colorScale="ContinuousColorScale;0.0;5.0;255,255,255;0,0,178" fontSize="10" height="120" id="/Users/jrobinso/igv-team Dropbox/James Robinson/projects/igv/test/data/bed/test.bed" name="Test Bed" visible="true"/>
>     </Panel>
>     <PanelLayout dividerFractions="0.0062827225130890054"/>
>     <HiddenAttributes>
>         <Attribute name="DATA FILE"/>
>         <Attribute name="DATA TYPE"/>
>         <Attribute name="NAME"/>
>     </HiddenAttributes>
> </Session>
> ```

**Comment by flyingicedragon** [comment] 2021-01-05 07:52
@jrobinso Maybe I find the problem. If I use absolute path and symbol link or relative path without symbol link, igv works great. If I use relative path and symbol link, igv can not work.

If I use `locus="All"` in `<Session genome="ITAG4.0" hasGeneTrack="true" hasSequenceTrack="true" locus="All" version="8">`, igv will not report error before I zoom in.

I have try version 2.8.9, 2.8.12 and 2.8.13.

**Comment by jrobinso** [comment] 2021-01-06 00:45
Has that combination ever worked, in any version of IGV?  Its possible Java cannot resolve the symbolic link to construct an absolute path, which must be done before loading.  This might be a limitation we cannot work around.

**Comment by flyingicedragon** [comment] 2021-01-06 06:34
@jrobinso The path in stdout is right.
```
INFO [2021-01-06T14:28:36,966]  [TrackLoader.java:122] [Thread-5]  Loading resource, path /home/icedragon/test1/test2/test3/test.bed
INFO [2021-01-06T14:28:41,828]  [MessageUtils.java:76] [pool-2-thread-2]  Error loading features for interval: SL4.0ch00:0-9643250 <br>java.lang.NullPointerException
ERROR [2021-01-06T14:28:41,829]  [FeatureTrack.java:739] [pool-2-thread-2]  Error loading features for interval: SL4.0ch00:0-9643250 <br>java.lang.NullPointerException
java.lang.NullPointerException: null
        at org.broad.igv.track.FeatureTrack.loadFeatures(FeatureTrack.java:722) [igv.jar:?]
        at org.broad.igv.track.FeatureTrack.load(FeatureTrack.java:691) [igv.jar:?]
        at org.broad.igv.ui.IGV.lambda$repaint$8(IGV.java:2389) [igv.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
Session file:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Session genome="ITAG4.0" hasGeneTrack="true" hasSequenceTrack="true" locus="All" version="8">
    <Resources>
        <Resource path="test/test.bed"/>
    </Resources>
    <Panel height="1122" name="FeaturePanel" width="2541">
        <Track attributeKey="Reference sequence" clazz="org.broad.igv.track.SequenceTrack" fontSize="10" id="Reference sequence" name="Reference sequence" visible="true"/>
        <Track attributeKey="Gene" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" colorScale="ContinuousColorScale;0.0;238.0;255,255,255;0,0,178" fontSize="10" height="35" id="ITAG4.0_genes" name="Gene" visible="true"/>
        <Track attributeKey="test.bed" clazz="org.broad.igv.track.FeatureTrack" color="0,0,178" colorScale="ContinuousColorScale;0.0;1.0;255,255,255;0,0,178" fontSize="10" id="/home/icedragon/test/test.bed" name="test.bed" visible="true"/>
    </Panel>
    <PanelLayout dividerFractions="0.00529567519858782"/>
</Session>
```

`test/` links to `/home/icedragon/test1/test2/test3/`

**Comment by jrobinso** [comment] 2021-01-09 06:08
@flyingicedragon I can't reproduce the problem on MacOS, relative path with symbolic link works fine.   If its not working on Linux its not working, its not likely to get fixed without a pull request as I don't have a linux box.    There is a preference to use absolute paths for sessions if that is helpful

**Closed** 2021-01-27 16:20 UTC
