### ISSUE TITLE
read view getting cut off

### ISSUE THREAD

**Issue by arvindpattamatta** [igvteam/igv#985] opened 2021-06-19 16:14 UTC
i have a similar issue with my reads (3000 x) getting cutoff at the bottom beyond 1000 X. Does the viewer memory shows only up to 1000 X ?
However, all reads are seen in squished mode. Any way to rectify this issue?
I see the same issue was raised by another person 10 days ago.

**Comment by jrobinso** [comment] 2021-06-20 12:17
I'm not sure what issue you are referencing re "similar issue", but no, there is no way to rectify this right now.   I discovered there is an absolute pixel height of 16kb in Java itself, the application can't do anything about it.   It will require a redesign, no ETA on that.  Since there is already an issue open for this I'm closing this one.

**Closed by jrobinso** 2021-06-20 12:17 UTC

**Comment by jrobinso** [comment] 2021-06-23 03:06
Duplicate of #981
