### ISSUE TITLE
Variants being shown sporadically

### ISSUE THREAD

**Issue by Lenbok** [igvteam/igv#361] opened 2017-01-19 20:50 UTC
Hi, I've been using current master and have an issue with variant track contents sometimes not being displayed. You did say in my other issue that master is in a state of flux, so feel free to say "just use the PRE_INS tag" :-), but thought you might not already know about this.

Here are a couple of screenshots:

![image](https://cloud.githubusercontent.com/assets/282098/22124516/04045004-def5-11e6-86f0-b5a1c1c28c5e.png)

![image](https://cloud.githubusercontent.com/assets/282098/22124537/2406e9c0-def5-11e6-9254-6635903e5898.png)

The variant track is only displayed when the marker lines are with 14 bases to the right of the coordinate of the variant.

If I zoom out, the variant track contents are never displayed:
![image](https://cloud.githubusercontent.com/assets/282098/22124700/c21031e4-def5-11e6-9bd1-45a6f90e26c2.png)

**Comment by jrobinso** [comment] 2017-01-19 21:07
Thanks I wasn't aware of that.   What are the "marker lines" you are referring to?   ("The variant track is only displayed when the marker lines").   


I appreciate the testing,  but for real work use PRE_INS.

**Comment by Lenbok** [comment] 2017-01-19 21:13
The marker lines I am referring to are the vertical indicators shown in the alignment track.

:+1:  PRE_INS

**Comment by jrobinso** [comment] 2017-01-20 00:11
I'm not able to reproduce this using 1KG data (session attached).     Do
you see the problem if you load this session?

**Comment by Lenbok** [comment] 2017-01-20 01:21
I could not reproduce it with your session so far. I then tried re-loading my session that originally had the problem, and can not consistently trigger it - I have had it happen once more, where things were fine at the most zoomed in level, but missing one level above (like my third screen shot). I will keep an eye on it and will let you know if I work out how to trigger it.

**Comment by jrobinso** [comment] 2017-01-20 06:14
OK, I'll study the VCF track code and see if I can spot a culprit.

**Comment by jrobinso** [comment] 2017-02-07 20:12
I can't reproduce this,  there were several checkins that might have fixed it.  I'm closing but reopen if you see it again.

**Closed by jrobinso** 2017-02-07 20:12 UTC

**Comment by Lenbok** [comment] 2017-03-02 22:31
Not sure how to actually reopen this, but I am still seeing the problem, and have what seems to be a way of reliably reproducing. Looks to involve the remote interface (which is the primary way I drive IGV).

* Start IGV
* Select Human (1kg, b37+decoy)
* Select MT
* Click zoom in button three times
* Load the attached VCF from [igv-test.zip](https://github.com/igvteam/igv/files/815263/igv-test.zip) *using the remote interface*
* Click the zoom out button two or three times
* Observe that variants are only shown for a subset of the region.

![image](https://cloud.githubusercontent.com/assets/282098/23529919/61253cb4-0004-11e7-92bc-94e4df15d040.png)


(If you remove the track and add it while zoomed out, all the variants are visible).
![image](https://cloud.githubusercontent.com/assets/282098/23529985/9e95570a-0004-11e7-976d-47c5842ea5ce.png)

This is with current master, 09b5583

**Comment by jrobinso** [comment] 2017-03-02 22:37
Thanks for the report and test data.  What exactly do you mean by "remote
interface"?

**Comment by Lenbok** [comment] 2017-03-02 22:46
Using port commands. I regularly use the following bash function to interact with IGV since I mostly use a terminal and find the Java file chooser abysmal :-)

````bash
# Convenience function that sends the arguments to a running IGV instance remote control port (assuming localhost and port 60151)
# See https://www.broadinstitute.org/igv/PortCommands for available commands
# In particular:
#   load <filename>
#   goto <region>
#   snapshot <filename>
function igv-cmd () {
    if [[ ! "$1" ]]; then
        cat<<EOF
Usage: igv-cmd COMMAND

For example:
  igv-cmd load <filename>
  igv-cmd goto <region>
  igv-cmd snapshotDirectory <dirname>
  igv-cmd snapshot <filename>

See https://software.broadinstitute.org/software/igv/PortCommands for full list of available commands
(or see org.broad.igv.batch.CommandExecutor for the source)

EOF
    else
        if [[ "$1" == "load" ]]; then
          local f="$2"
          if [[ "$f" != /* ]]; then
            f="$PWD/$f"
          fi
          echo "$1 $f" | nc localhost 60151
        else
          echo "$@" | nc localhost 60151
        fi
    fi
}
````

This lets me do things like:
````
  $ igv-cmd load ~/snps.vcf.gz
````

**Comment by Lenbok** [comment] 2017-03-15 04:08
@jrobinso Were you able to replicate the problem with the data I sent? I have been having a poke but am not having any luck working out the cause of the bug.

**Comment by jrobinso** [comment] 2017-03-15 04:38
No time to try yet, but if you're working off of master its in a lot of
flux,  I'm working through bam issues now.   Sorry but there are only so
many hours in a day,  and I am 1 person.  It will get sorted.
