### ISSUE TITLE
CRAM file reference checksum mismatch problem (GRCh38)

### ISSUE THREAD

**Issue by kelepiradam** [igvteam/igv#883] opened 2020-12-30 16:32 UTC
Hi 

I have just started using the GATK broad repository GRCh38 for my alignment works however IGV hg38 shows a checksum mismatch between my reference genome and IGV downloaded hg38 reference genome. 

![image](https://user-images.githubusercontent.com/37572619/103367222-9c8e6800-4ad5-11eb-908b-6c48a944b93c.png)

What should I do? Should I trust the GATK Resource bundle and use that genome as downloaded genome or should I stop using it? 

CRAM file was generated using latest samtools. 

Regards.

**Comment by jrobinso** [comment] 2020-12-30 19:23
That should not happen if your reads were aligned to hg38.   Could you extract the header from your CRAM file, zip it, and attach it here?

**Comment by kelepiradam** [comment] 2020-12-30 19:52
Sure. 
[header.txt.gz](https://github.com/igvteam/igv/files/5755533/header.txt.gz)

**Comment by jrobinso** [comment] 2020-12-30 21:46
I can reproduce this with a 1KG Cram for the location in your screenshot, but not for other locations.   At the moment I don't know if there really is a difference in sequence there, which would be strange,  or if there is a bug in the CRAM library.   Have you tried using the fasta the reads were aligned to, rather than "hg38"?

**Comment by kelepiradam** [comment] 2020-12-30 23:16
When I replace the downloaded fasta with the reference genome fasta file from gatk resource bundle error message goes away and I can see the mapped reads without issues.

**Comment by kelepiradam** [comment] 2020-12-30 23:39
Looks like it is a soft masked reference issue. 

```
36,37c36,37
< ATCCGCGTTGTTCCGTGTTGGGGGCGGCATGGAGCGGGAGCCGGGCGCCGCGGGAGTTCG
< CCGGGCTCTGGGCCGCCGGCTGGAGGCGGTGCTGGCGAGCCGCAGTGAGGCCAACGCCGT
---
> ATCCGCGTTGTTCCGTGTTGGGGGCGGCATGGAGcgggagccgggcgccgcgggagttcg
> ccgggctctgggccgccggCTGGAGGCGGTGCTGGCGAGCCGCAGTGAGGCCAACGCCGT
39,40c39,40
< CACGGGAGCGGGACTTGAATGGGGGGCTGCGGCGGCAGGTCCCCAGGAGGTTCCGAGACG
< GCGTTGGGGGGTCAGGGTGGGAGGCGTGTGGGTCACGGGTCGGGGGTGACGGGGCTGGCG
---
> CACGGGAGCGGGACTTGAATGGGGGGCTGCGGCGGCAGGTCCCCAGGAGGTTCCGAGAcg
> gcgttggggggtcagggtgggaggcgtgtgggtcacgggtcgggggtGACGGGGCTGGCG
61,77c61,77
< ACACTGTGGTCTGCAGCCATGGGAATGCATTATGAGCTTTCTTAAAATCTGTAGTGAGGA
< ATAACTGAGGCACAGTTTACCGTTTAAAGCTGAGAAGTTAGCATCTGTTACTGTGTTGTG
< CAGTGGTTGCCGCTATCCCAGAACATCTTTATCGCCCCGAAAAGAAATCCTGTACCAGTT
< ACCATCGCTTCCATATCCCGCCCCTTTCCACCCCCAGCCCCAGGCAGCCACTCCTGGATC
< AGTGGTTACTTCCTGGATCAATGGGTTTGCTTTTTTTAGACGCTCCTCATAAGGGGGATC
< ATACGGTATGTGGCTTCTTCCACTCATCGGCGTGTTCGAAGTTCGTTCTCTTTGTGGCTG
< AGTAGCAGCGCGTCGTATAGCACAGCACGTATCGTTCAGCCGCTCGTAGGTTGCTGGGCA
< TTTGCGTCGTTTCCACCTTTGGCTGTTACGAACAGCGGACTGTGAACGTTCGCGTACAAA
< CTCTTGTGTGATGTTTCTTTTGCTTGAATATGCCTTATCAGTGGAATTACAAGGCCACAC
< AGCAGCTGTGTTTTTAATGTTCTGAGGAACTACAAGACTGTTTTCCATAGTAGCTGCGCT
< ATCTTACCCTCCCCCTGGCAGCATTTGAGAGTTCCATACTCCACATCCTCGCCAACACGT
< CTGTCTATAATTATAGCCGAGCTGCAGACTTTTAAATGTTGGGGAGATACCACGTGAAAA
< TAACCAGTTTCCACCTTCTCAGAAAGAAATAATCAGTTCTGTCAACACGGGGTCTAAGTT
< TGTTCATGGCTGCGATTGGCTGGAGGGAGAGTCAGAGACAGCTCTGAGACAGCCGTGTGC
< TCCTGTCATCCCGCACGAGGCTCTTTTGCTTTGTGGTGTCATTTGCCTGGGCCCTGAAAG
< CACTGAGTTTGCCACCCCGAGATGAGAGCTTCCAAGCCTGGGTCTGAGTTGGGCACCATG
< CTGGCATCACACGCCTGTGTTTTCACAGCTGTTCCCAAGGGTTATGGTGGCATTCCCGTG
---
> ACACTGTGGTCTGCAGCCATGGGAATGCATTATGAGCtttcttaaaatctgtagtgagga
> ataactgaggcacagtttaccgtttaaagctgagaagttagcatctgttactgtgttgtg
> cagtggttgccgctatcccagaacatctttatcgccccgaaaagaaatcctgtaccagtt
> accatcgcttccatatcccgcccctttccacccccagccccaggcagccactcctggatc
> agtggttacttcctggatcaatgggtttgctttttttagacgctcctcataagggggatc
> atacggtatgtggcttcttccactcatcggcgtgttcgaagttcgttctctttgtggctg
> agtagcagcgcgtcgtatagcacagcacgtatcgttcagccgctcgtaggttgctgggca
> tttgcgtcgtttccacctttggctgttacgaacagcggactgtgaacgttcgcgtacaaa
> ctcttgtgtgatgtttcttttgcttgaatatgccttatcagtggaattacaaggccacac
> agcagctgtgtttttaatgttctgaggaactacaagactgttttccatagtagctgcgct
> atcttaccctccccctggcagcatttgagagttccatactccacatcctcgccaacacgt
> ctgtctataattatagccGagctgcagacttttaaatgttggggagataccacgtgaaaa
> taaccagtttccaccttctcagaaagaaataatcagttctgtcaacacggggtctaagtt
> tgttcatggctgcgattggctggagggagagtcagagacagctctgagacagccgtgtgc
> tcctgtcatcccgcacgaggctcttttgctttgtggtgtcatttgcctgggccctgaaag
> cactgagtttgccaccccGAGATGAGAGCTTCCAAGCCTGggtctgagttgggcaccatg
> ctggcatcacacgcctgtgttttcacagctgttcccaagggttatggtggcattcCCGTG
140,142c140,142
< GCCGCCGCCTCGCTCACACCACACCCCTAATCCCCTCGGTGAGTGCCGCCGCCTCGCTCA
< CACCCCCAACCCCCACCCCGCAGCACCTCTTCCCCGATCCCACTGCCTCCACCCCCCACT
< CCCCTGCCCTGCATGTGGTCTCCAGCTTTGTGTCCGTGGGGGCTGTGGGAGGGGACAGCA
---
> GCCGCCGCCTCGCTCACACCACACCCCTAATCCCCTCGGTGAGTGCCGCCGCCTCGCTca
> cacccccaacccccaccccgcagcacctcttccccgatcccactgcctccaccccccact
> ccccTGCCCTGCATGTGGTCTCCAGCTTTGTGTCCGTGGGGGCTGTGGGAGGGGACAGCA
146c146
< CAGGTCTTCTTCCCAGTCTGCCCAGCCCTGCTCCTCTGTCCCCTTCCCACCCTGCCCCAC
---
> CAGGTCTTCTTCCCAGTctgcccagccctgctcctctgtccccttcccaccctgcccCAC
```

This is the result of the diff command  for gatkresourcebundle.fasta igv.fasta. IGV's fasta from amazon repository seems to be soft masked therefore the checksum is different for the NOC4L locus that I was searching. 

Same difference is also true between the Heng Li's recommended fasta file for hg38 without alt mapping and IGV's fasta from amazon repository.

**Comment by kelepiradam** [comment] 2020-12-30 23:53
And looks like this will be a problem for many other loci as well
```
Contig | GATK RB Length | IGV Length | GATK RB md5 | IGV md5 | Length Comparison | md5 Comparison
chr1 | 248956422 | 248956422 | 6aef897c3d6ff0c78aff06ac189178dd | 2648ae1bacce4ec4b6cf337dcae37816 | Match | No Match
chr2 | 242193529 | 242193529 | f98db672eb0993dcfdabafe2a882905c | 4bb4f82880a14111eb7327169ffb729b | Match | No Match
chr3 | 198295559 | 198295559 | 76635a41ea913a405ded820447d067b0 | a48af509898d3736ba95dc0912c0b461 | Match | No Match
chr4 | 190214555 | 190214555 | 3210fecf1eb92d5489da4346b3fddc6e | 3210fecf1eb92d5489da4346b3fddc6e | Match | Match
chr5 | 181538259 | 181538259 | a811b3dc9fe66af729dc0dddf7fa4f13 | f7f05fb7ceea78cbc32ce652c540ff2d | Match | No Match
chr6 | 170805979 | 170805979 | 5691468a67c7e7a7b5f2a3a683792c29 | 6a48dfa97e854e3c6f186c8ff973f7dd | Match | No Match
chr7 | 159345973 | 159345973 | cc044cc2256a1141212660fb07b6171e | 94eef2b96fd5a7c8db162c8c74378039 | Match | No Match
chr8 | 145138636 | 145138636 | c67955b5f7815a9a1edfaa15893d3616 | c67955b5f7815a9a1edfaa15893d3616 | Match | Match
chr9 | 138394717 | 138394717 | 6c198acf68b5af7b9d676dfdd531b5de | addd2795560986b7491c40b1faa3978a | Match | No Match
chr10 | 133797422 | 133797422 | c0eeee7acfdaf31b770a509bdaa6e51a | 907112d17fcb73bcab1ed1c72b97ce68 | Match | No Match
chr11 | 135086622 | 135086622 | 1511375dc2dd1b633af8cf439ae90cec | 1511375dc2dd1b633af8cf439ae90cec | Match | Match
chr12 | 133275309 | 133275309 | 96e414eace405d8c27a6d35ba19df56f | e81e16d3f44337034695a29b97708fce | Match | No Match
chr13 | 114364328 | 114364328 | a5437debe2ef9c9ef8f3ea2874ae1d82 | 17dab79b963ccd8e7377cef59a54fe1c | Match | No Match
chr14 | 107043718 | 107043718 | e0f0eecc3bcab6178c62b6211565c807 | acbd9552c059d9b403e75ed26c1ce5bc | Match | No Match
chr15 | 101991189 | 101991189 | f036bd11158407596ca6bf3581454706 | f036bd11158407596ca6bf3581454706 | Match | Match
chr16 | 90338345 | 90338345 | db2d37c8b7d019caaf2dd64ba3a6f33a | 24e7cabfba3548a2bb4dff582b9ee870 | Match | No Match
chr17 | 83257441 | 83257441 | f9a0fb01553adb183568e3eb9d8626db | a8499ca51d6fb77332c2d242923994eb | Match | No Match
chr18 | 80373285 | 80373285 | 11eeaa801f6b0e2e36a1138616b8ee9a | 11eeaa801f6b0e2e36a1138616b8ee9a | Match | Match
chr19 | 58617616 | 58617616 | 85f9f4fc152c58cb7913c06d6b98573a | b0eba2c7bb5c953d1e06a508b5e487de | Match | No Match
chr20 | 64444167 | 64444167 | b18e6c531b0bd70e949a7fc20859cb01 | b18e6c531b0bd70e949a7fc20859cb01 | Match | Match
chr21 | 46709983 | 46709983 | 974dc7aec0b755b19f031418fdedf293 | 2f45a3455007b7e271509161e52954a9 | Match | No Match
chr22 | 50818468 | 50818468 | ac37ec46683600f808cdd41eac1d55cd | 221733a2a15e2de66d33e73d126c5109 | Match | No Match
chrX | 156040895 | 156040895 | 2b3a55ff7f58eb308420c8a9b11cac50 | 49527016a48497d9d1cbd8e4a9049bd3 | Match | No Match
chrY | 57227415 | 57227415 | ce3e31103314a704255f3cd90369ecce | b2b7e6369564d89059e763cd6e736837 | Match | No Match
chrM | 16569 | 16569 | c68f52674c9fb33aef52dcf399755519 | c68f52674c9fb33aef52dcf399755519 | Match | Match
```

**Comment by kelepiradam** [comment] 2020-12-31 00:07
I was about to test the same thing for 1kg_v37 genome from IGV and hs37d5 from 1KG but fresh installed IGV seems to be acting on its own 

![image](https://user-images.githubusercontent.com/37572619/103387509-43debf80-4b15-11eb-960c-13e4faec9362.png)

Looks like it no longer downloads the bgzipped fasta files from amazon but whole unzipped fasta in a weird way.

**Comment by jrobinso** [comment] 2020-12-31 04:42
Soft masking (upper vs lower case) is not the cause,  the sequence really does differ in at least 1 place.   At position 122093260   "hg38" has an N,  but the GRch38 assembly has a Y.   I am guessing its a similar issue for the other sequences in your table.  So the only solution is to use the GRch38 fasta, probably any of the extant versions will do.   Technically you should use the fasta the CRAM file was aligned to, if you can find it.

I will add a hosted "GRch38" genome in the next few days.

**Comment by kelepiradam** [comment] 2020-12-31 06:43
You are right I missed that point. So I will be using the gatk resource grch38 as the installed genome file. Thanks for the immediate followup in this issue.

**Comment by jrobinso** [comment] 2021-01-01 01:22
This use of ambiguity codes in the DNA reference is not part of the "standard" GRCh38 fasta as far as I can tell, it seems peculiar to the GATK and some 1KG crams.   I'm sure there is a reason for it, but what it means is those CRAMS cannot be decoded against the standard references.    @droazen might have some insight here. 

I will deploy the GATK hg38 assembly as a hosted reference, not sure what to call it but it will have GATK in the name.    Its possible many of the 1KG crams were also aligned against this sequence,  I'm not sure that all of them would have been though.

**Comment by jrobinso** [comment] 2021-01-06 00:48
Closing this as there really isn't anything to fix here, its the nature of CRAM files.

**Closed by jrobinso** 2021-01-06 00:48 UTC
