### ISSUE TITLE
IGV hang on goto command in batch file

### ISSUE THREAD

**Issue by woodoo46** [igvteam/igv#849] opened 2020-09-14 14:53 UTC
Hi IGV developers,

I am using IGV on Ubuntu, I found sometimes IGV hang on the goto command in a batch file. I am using IGV on a local machine, no ssh forwarding. Any suggestion? 

Thanks!

George

**Comment by jrobinso** [comment] 2020-09-15 02:05
You haven't given us enough information to make suggestions.   Check that you are using the latest IGV release.

**Comment by hydriniumh2** [comment] 2020-09-21 20:11
I'm having the same issue, this is running igv 2.8.8 with openjdk 11.0.8 on Ubuntu 20.
With the following batch file:
```
new
setSleepInterval 500
preference IGV.chart.track.height 40
preference IGV.track.height 4000
preference NAME_PANEL_WIDTH 200
preference SAM.SHOW_SOFT_CLIPPED TRUE
preference SHOW_REGION_BARS TRUE
preference SCALE_FONTS TRUE
preference SAM.MAX_VISIBLE_RANGE 1000
preference SAM.DISPLAY_MODE SQUISHED
preference SAM.COLOR_BY READ_STRAND
preference SAM.SHOW_MISMATCHES TRUE
preference SAM.SHOW_ALL_BASES FALSE
preference SAM.FILTER_SECONDARY_ALIGNMENTS FALSE
preference SAM.QUALITY_THRESHOLD 0
snapshotDirectory {params.output_dir}
genome {genome}
load {bam}
squish {bam}
goto {contig}
snapshot {name}.png
```
using the command
`igv -b snapshot_indels.txt`
Which runs the following default igv script:
```
#!/bin/sh

#This script is intended for launch on *nix machines

#-Xmx4g indicates 4 gb of memory, adjust number up or down as needed
#Add the flag -Ddevelopment = true to use features still in development
#Add the flag -Dsun.java2d.uiScale=2 for HiDPI displays
prefix=`dirname $(readlink $0 || echo $0)`

# Check whether or not to use the bundled JDK
if [ -d "${prefix}/jdk-11" ]; then
    echo echo "Using bundled JDK."
    JAVA_HOME="${prefix}/jdk-11"
    PATH=$JAVA_HOME/bin:$PATH
else
    echo "Using system JDK."
fi

exec java -showversion --module-path="${prefix}/lib" -Xmx4g \
    @"${prefix}/igv.args" \
    -Dapple.laf.useScreenMenuBar=true \
    -Djava.net.preferIPv4Stack=true \
    --module=org.igv/org.broad.igv.ui.Main "$@"
```
This is run on a small bam file which is comprised of reads aligned to 3 amplicons of 12925 and 8000 basepair length
This is the .fai
```
WT	12925	74	60	61
INV	12925	13290	60	61
DEL	8000	26505	60	61
```
So the goto command would be`goto DEL` for example.
Any help would be greatly appreciated.
Thanks!

**Comment by jrobinso** [comment] 2020-09-21 21:48
I can't really help without a reproducible test case.   If you can zip up a test case and make it available I will look at it.  

I might also suggest you try the latest "snapshot" version,  there are a  number of structural changes to the code there that might impact batch running.   These will be released later in the fall, but are availabe now from the "snapshot" downloads (or you can pull and build yourself).

**Comment by hydriniumh2** [comment] 2020-09-22 15:23
Actually nvm I forgot to mention I'm running igv pseudo-headless using xvfb-run with the command `xvfb-run --auto-servernum --server-args="-screen 0 3200x2400x24" igv -b snapshot_indels.txt` so its not exactly a recommended usage of igv. After more checking its likely due to an issue with xvfb-run and its interaction with igv rather than an issue with igv itself.

**Comment by woodoo46** [comment] 2020-09-24 01:00
My case is very simple:
This is the template I used to write a set of regions

genome hg38
load ${bamfile}
region ${E[0]} ${E[1]} ${E[2]}
goto ${E[0]}:${x}-${y}
group STRAND
snapshot ${E[0]}:${x}-${y}.png
exit

After a specific file is generated:

~/mytools/IGV_Linux_2.8.9/igv.sh -b igv_batch.txt

In some cases, I can see the IGV window is displayed, and then closed; but most of the cases, the window is stuck on the screen.

**Comment by elcortegano** [comment] 2020-09-25 15:22
I think the problem goes in the direction pointed out by @hydriniumh2 . I recently noted IGV hangs in a system where I'm running Ubuntu 20.04, both when making the call with `igv.sh -b script.bat` and when using `xvfb`. However, it runs just fine in a separate system where I got Arch linux installed.

**Closed** 2020-11-10 06:07 UTC
