### ISSUE TITLE
Problems with fresh installation of IGV v2.10.3 on macOS

### ISSUE THREAD

**Issue by williamrowell** [igvteam/igv#1014] opened 2021-08-10 00:52 UTC
I set up v2.10.3 on a fresh laptop, changed the reference to `Human (hg38)`, and tried to load an IGV session by URL.  There were a couple problems, and I'm listing them together because it's likely they're connected, since I hadn't encountered them before with earlier versions on other laptops.
- even before loading the session, the cytobands were missing
- after loading, an error window popped up with the following message: `Error loading features for interval: chr6:43169269-43183506 java.lang.NullPointerException`
![image](https://user-images.githubusercontent.com/627365/128791460-b2ef75b8-6e45-4b99-a705-d6c937660ff2.png)

I've attached the session and log.
[igv.log](https://github.com/igvteam/igv/files/6958192/igv.log)
[HG002_igv.xml.gz](https://github.com/igvteam/igv/files/6958193/HG002_igv.xml.gz)

Have you seen something like this before with a fresh install?

**Comment by jrobinso** [comment] 2021-08-10 06:43
I'm not able to load your session because the host "100humansfs" is unknown.   Is this expected?

**Comment by jrobinso** [comment] 2021-08-10 14:59
I'm not sure what happened here, and can't load your session, however here is a suggestion.  Shutdown IGV and delete the files "/Users/wrowell/igv/genomes/hg38.json". and "/Users/wrowell/igv/genomes/hg38.genome".   Then restart and select Human (hg38) from the Genomes > Load from Server...  menu.

**Comment by williamrowell** [comment] 2021-08-10 15:05
Sorry, yes, my session was internal-only.  I'll find an external session to test on.

I tried removing the entire `~/igv` directory yesterday and allow IGV to recreate it, and got the same outcome.  I also switched to an older laptop with an existing IGV installation (~2.8.10) and was able to load the session I attached without any errors.  I also think all of the custom tracks in my session are displayed, despite the errors, so that makes me think this error is related to loading cytoband or refseq features.

**Comment by jrobinso** [comment] 2021-08-10 18:20
Thanks for the update.  I could reproduce the cytoband issue, and have rolled back the release to 2.10.2 while we investigate.  However from your log I'm not sure that's related to the null pointer error.  I suggest you just stay with 2.10.0 unless you need new features in 2.10.3.

**Comment by williamrowell** [comment] 2021-08-10 18:48
Thanks for the help troubleshooting this.  I rolled back to 2.10.0 and still couldn't see cytobands.  I closed the app, removed `~/igv`, and reopened, and now I can see cytobands and don't see the null pointer error when I load my (internal) example session.

**Comment by jrobinso** [comment] 2021-08-10 18:57
We are working towards a 2.11.0 release which will define genomes
with ".json" files, rather than ".genome" files.  I don't have a full
explanation of what happened here but I think the 2.10.3 release
inadvertently pulled .json files for genomes, and once the json genome was
in the "igv/genomes" directly IGV would attempt to use it.   That's not a
great explanation but its all I got.

**Comment by williamrowell** [comment] 2021-08-12 04:00
That's a good enough explanation for me.

**Comment by jrobinso** [comment] 2021-09-08 23:42
As I can't reproduce an error here, and 2.11.0 has been released, I'm closing this now.

**Closed by jrobinso** 2021-09-08 23:42 UTC
