### ISSUE TITLE
Batch script with large maxPanelHeight does not actually render all tracks

### ISSUE THREAD

**Issue by rlorigro** [igvteam/igv#1336] opened 2023-05-31 19:44 UTC
Hi,

I am trying to render a snapshot of a large number of VCF tracks( ~50), but even with maxPanelHeight of 10,000, it only renders the portion of VCF tracks that are visible in my open window.

![chr20_7901320-7901444](https://github.com/igvteam/igv/assets/28764332/326c0e12-179f-4577-b622-a73e022260ad)

Is there something else I need to change? I am running this from the GUI.

Thanks

**Comment by jrobinso** [comment] 2023-05-31 23:03
That looks like an IGV bug.  What version of IGV are you using?

**Comment by rlorigro** [comment] 2023-05-31 23:06
Version 2.16.1, on Ubuntu 22.04

I also loaded these tracks from a saved session, if that makes any difference

**Comment by jrobinso** [comment] 2023-05-31 23:52
Probably not, but can you post your batch script here?

**Comment by jrobinso** [comment] 2023-06-01 15:48
OK I can reproduce this, I don't need your batch script.   I think what's happening is after loading tracks are left scrolled out of view "above" the top of the view.   maxPanelHeight extends the screenshot as needed for data below the viewport.  It was intended primarily for BAM files,  a panel with many tracks was apparently never tested.    So its a bug, working on a fix.

**Comment by jrobinso** [comment] 2023-06-01 15:54
I do have a workaround you can try.  Before doing the snapshot, use the `scrolltotrack` command to scroll the view to the first track.   The command takes the name of the track as an argument  Example below.  

```
new
maxPanelHeight: 10000
goto chr1:637-9,175
load ../data/gff/canonical.eden.unsorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
load ../data/gff/canonical.eden.sorted.gff3
scrolltotrack canonical.eden.unsorted.gff3
snapshot
```

```

**Comment by rlorigro** [comment] 2023-06-01 16:08
Thanks, yes your script is essentially the same as mine. I have tested the workaround and it works as intended, too

**Comment by jrobinso** [comment] 2023-06-01 16:16
I'm adding a new command "scrollToTop" for the next release, which will scroll all panels to the top without needing to specify track name.   I hesitate to do this automatically as someone could have explicitly scrolled to a specific track.

**Comment by rlorigro** [comment] 2023-06-01 16:19
Thanks, I think that is totally reasonable

Unrelated (I can open a separate issue if you prefer) it seems that reducing the track height below 40 doesn't have the intended effect because there is a minimum padding of some kind that prevents close packing of the VCF tracks. I've tried "Fit Data to Window" and "Set Track Height". 

Obviously I am abusing the VCF track feature, but it would be convenient to be able to squash them more for this situation where I have lots of them, as opposed to merging them into a single VCF.

**Comment by jrobinso** [comment] 2023-06-01 17:50
@rlorigro Yes open another issue, or I might forget about this.

**Comment by jrobinso** [comment] 2023-09-02 02:35
scrollToTop will be in the next release, by the end of September.

**Closed by jrobinso** 2023-09-02 02:35 UTC
