### ISSUE TITLE
Bug in read info when doing view as read pairs

### ISSUE THREAD

**Issue by gevro** [igvteam/igv#1077] opened 2021-12-25 16:45 UTC
IGV 2.11.3

I think I found a bug when clicking on a read during 'View as read pairs', it is showing the wrong info. The start position of the read doesn't make sense. See screenshots.
<img width="925" alt="Screen Shot 2021-12-25 at 11 43 35 AM" src="https://user-images.githubusercontent.com/47928628/147389639-603261dd-5e7a-472c-a62f-00bed1cbb28b.png">
<img width="1202" alt="Screen Shot 2021-12-25 at 11 44 04 AM" src="https://user-images.githubusercontent.com/47928628/147389640-0a24ad3e-bb74-4e64-9c7b-4362e7c53c63.png">

**Comment by gevro** [comment] 2021-12-25 16:48
Zooming in doesn't fix the problem. See this screenshot zoomed in. The info is for the read below the info box.
I'm not even sure how to replicate this because it is such a bizarre bug.

<img width="1196" alt="Screen Shot 2021-12-25 at 11 47 18 AM" src="https://user-images.githubusercontent.com/47928628/147389688-59e0235d-95af-4c20-b3cf-5b1bd5582323.png">

**Comment by gevro** [comment] 2021-12-25 16:51
Some more info-- I am doing:
1) View as read pairs
2) Sort alignment by start location.

I suspect what might be happening is that the location where my mouse click is is not registered correctly with IGV, so that IGV is showing me info for a read I'm not actually pointing to. Just an idea.

**Comment by jrobinso** [comment] 2021-12-28 05:03
I can't tell what read you clicked on for these screenshots so they aren't
really helpful.  However I tried reproducing it unscucessfully.   I'm
testing the latest release.

**Comment by gevro** [comment] 2021-12-28 05:08
I clicked on this read:
![147389688-59e0235d-95af-4c20-b3cf-5b1bd5582323](https://user-images.githubusercontent.com/47928628/147530203-c96725d3-7c8c-4868-a27f-f62a98e249c5.png)

You can see from the coordinates at the top that neither the primary nor the mate coordinates should be within the current window.

This is on MacOS.

**Comment by jrobinso** [comment] 2021-12-28 05:12
OK, but as I said I can't reproduce it with the latest release.   Try the
latest release,  if it still occurs I will probably need a test case I can
reproduce,  I've tried it with no success.   See if you can reproduce it
with our public bams (Load from sever for hg19), and if you can give me
exact instructions.

**Comment by gevro** [comment] 2021-12-28 05:16
Ok. I will be in touch if I can get an exact procedure that reproduces it reliably.

**Comment by helgathorv** [comment] 2022-01-13 16:24
Closing this for now, but we'll re-open if a test case is found that reproduces the problem.

**Closed by helgathorv** 2022-01-13 16:24 UTC
