### ISSUE TITLE
fonts scale no effect in ubuntu

### ISSUE THREAD

**Issue by indexofire** [igvteam/igv#290] opened 2016-07-26 01:21 UTC
My personal laptop is running ubuntu 16.04 + i3wm with 4k dpi. I have switched scale to 2 (192dpi) so the system scale is fine. but it's doesn't work for igv 2.3.79 even I turn on scale fonts in perference or adding parameter '-Dis.hidpi=true' in init script.

anyway running igv via jnlp is also tiny fonts without scaling.

thanks anyway.

**Comment by jrobinso** [comment] 2016-07-26 02:30
Have  you tried other java programs, and do they work?  If so can you point us to one?   Also, what Java are you running, and have you tried alternatives?

We don't have that equipment & OS so its hard to say what the problem is.

**Comment by jrobinso** [comment] 2016-07-26 12:28
From reading various boards on this topic it appears that this is a known issue, with OpenJDK at least, perhaps Oracle Java also, and there are no easy workarounds.   It has reportedly been fixed in OpenJDK 9,  so if you are able to run that version it might solve the problem.  If you do this could you report the result back here,  good or bad?

**Comment by indexofire** [comment] 2016-07-26 15:44
thanks for the reply. the topic scaling failure is on openjdk-8. Then I installed oracle-9(someone said fixing hidpi fonts display) from ppa:webupteam which only raise a "javax.xml.bind.JAXBException" error when running igv.sh. And I get no error msg, just break, when running Mauve.

After that, I installed oracle-8, the same as openjdk-8, no scaling effect.

Last I tried openjdk-9, when I run igv, the program crashed. the std error showed:
...
# Problematic frame:
# C  [libjava.so+0x1d009]  JNU_GetEnv+0x19
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %P" (or dumping to /home/mark/app/igv/core.13448)
...

**Comment by jrobinso** [comment] 2016-07-27 22:30
I will see if I can reproduce and fix the JAXBException problem.   The 
core-dumps are library issues on your machine, there's nothing that I 
know of we can do about it.  Perhaps you have to upgrade some libs to 
use it.   The issue of font scaling on high-res displays with Java Swing 
is easy to google and follow, reportedly its been fixed on OpenJDK-9 and 
I hope also on Oracle-9 but I have no way to independently verify that 
as I don't have that equipment.   It works fine on Mac high res displays 
even with Java 7.

I asked about other Java programs,  if you can find another Java Swing 
program that behaves correctly point us to it and if the source is 
available maybe we can figure out how they got it to work.

**Closed** 2018-10-25 20:43 UTC
