### ISSUE TITLE
Can't change track height when viewing bed12 files in squished mode using Mac version

### ISSUE THREAD

**Issue by GenomeRIK** [igvteam/igv#835] opened 2020-08-05 16:19 UTC
Hello,

Thank you for this wonderful tool! I am using IGV 2.8.9 on a Mac and I am trying to view Bed12 files representing a transcriptome annotation. When I put the track mode into squished the track height is way too large and has a lot of white space below the transcript models. I tried changing the track height but it kept going back to the same height (2249). this is for viewing 13 transcript models in the window. 

The track height change option works when I view in collapse mode. 

<img width="952" alt="igv_track_height2" src="https://user-images.githubusercontent.com/29868736/89437592-afc42400-d73f-11ea-96de-7eb30f6840b6.png">

Is this a bug or some kind of hard limit for track heights in squished mode?

Thank you,
Richard

**Comment by jrobinso** [comment] 2020-08-07 22:40
Looks like a bug to me, however I can't reproduce it.  How did you switch to "squished" mode? 

Below is the refseq track in "squished" mode, with another track below it. 

<img width="1257" alt="Screen Shot 2020-08-07 at 3 36 24 PM" src="https://user-images.githubusercontent.com/933148/89693758-46215280-d8c4-11ea-843e-521067fa3604.png">

**Comment by GenomeRIK** [comment] 2020-08-17 17:30
Hello,

Sorry for taking so long to get back to you on this. I am switching to "squished" mode by right clicking on the track and selecting "squished" from the pop up window. 
<img width="1190" alt="igv_issue_squished_screenshot" src="https://user-images.githubusercontent.com/29868736/90425471-ad56b800-e0b7-11ea-9e2d-21dfc087be10.png">

Thank you,
Richard

**Comment by jrobinso** [comment] 2020-08-17 23:36
OK, the problem is I can't reproduce it.    Is it possible to share your data file,  or can you reproduce it with our public hosted files?

**Comment by jrobinso** [comment] 2020-11-10 06:11
Closing as I can't reproduce this.  To re-open please provide a reproducible test case.

**Closed by jrobinso** 2020-11-10 06:11 UTC
