### ISSUE TITLE
NullPointerException problem

### ISSUE THREAD

**Issue by L1feone** [igvteam/igv#813] opened 2020-06-01 06:47 UTC
Hi!

I mapped paired end library to a genome. Now I am trying to visualise it via IGV, but I am always getting this message when trying to jump to a certain chromosome: "Error encountered querying alignments: java.lang.NullPointerException". Reference genome has 19 chromosomes and a lot of unplaced genomic scaffolds. Jumping to these scaffolds does not cause an error. Only when I am picking a chromosome. Bam file is sorted and indexed, Reference file headers and bam headers are same and in the same order.

Tablet and IGB don't have these problems, but I want to use IGV.

I found a few old topics in the internet with the same problem, but didn't find any solution.

Help please.

Thank you.

**Comment by L1feone** [comment] 2020-06-01 15:30
IGV version is 2.8.2 
BAM file is 32mb so I uploaded it do google disc:

https://drive.google.com/file/d/1ff2mEB1oPrnSGelQEvSbWCcw9KsPBisc/view?usp=sharing

**Comment by jrobinso** [comment] 2020-06-01 15:44
What locus (genome location) do you encounter this error?  Is the bam file indexed?

**Comment by L1feone** [comment] 2020-06-01 15:48
BAM file indexed. Error occures with every chromosome wich name starts with NC_######

**Comment by jrobinso** [comment] 2020-06-01 20:24
I need a fasta file to load this.  Is the fasta reference available online?

**Comment by L1feone** [comment] 2020-06-01 20:35
Yes, here it is: 

https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_other/Nothobranchius_furzeri/latest_assembly_versions/GCF_001465895.1_Nfu_20140520/GCF_001465895.1_Nfu_20140520_genomic.fna.gz

**Comment by jrobinso** [comment] 2020-06-01 20:35
OK I downloaded the fasta for one of the sequences, NC_029651.1,  and was able to load the file with no problem.  I went to locus NC_029651.1:12,142,889-12,146,819  (see screenshot).  To look into this further I need exact steps from you to reproduce, including a locus that reproduces the problem.   Also, as I requested earlier, the contents of igv.log would be helpful.  Its in an "igv" folder in your home directory.    When you've supplied these things I will look further.  Thanks for your report.
<img width="831" alt="Screen Shot 2020-06-01 at 1 32 22 PM" src="https://user-images.githubusercontent.com/933148/83451949-a3a0ab00-a40c-11ea-8d71-3929da614814.png">

**Comment by L1feone** [comment] 2020-06-01 20:44
[igv.log](https://github.com/igvteam/igv/files/4713333/igv.log)

**Comment by L1feone** [comment] 2020-06-01 20:45
I just tried IGV 2.8.0 and everything worked out well.

**Comment by jrobinso** [comment] 2020-06-01 20:47
@L1feone could you answer my question re an exact locus to reproduce the problem?

**Comment by jrobinso** [comment] 2020-06-01 20:48
And another question,  what is you "visibility window" for alignments set to?

**Comment by jrobinso** [comment] 2020-06-01 20:53
OK I think I see the issue from your igv.log file.  This bug will occur in bam files without base qualities if a large visibility window is set.   A fix was pushed for it on April 7 but it is not released.  If 2.8.0 is working you can continue using that, or you can use the snapshot build from here:  https://software.broadinstitute.org/software/igv/download_snapshot until the next release, sometime in June.

**Comment by L1feone** [comment] 2020-06-01 21:03
Ok, thank you!
I will try the snapshot build.

By the way, an error occured with standart visibility window too. Should i still describe the specific steps which led to an error?

**Comment by jrobinso** [comment] 2020-06-01 21:40
@L1feone Yes if you don't mind, and I will test your steps to reproduce.    Its possible there is a separate bug.

Warning about the snapshot build, it is by its nature not stable, if you don't need features added since 2.8.0 I would stick with that version.

**Comment by L1feone** [comment] 2020-06-02 09:55
Ok, 2.8.0 suits me well)

My steps are: 
After opening IGV and choosing the genome I am loading my BAM file. Error occures when I choos a NC_###### chromosome. Choosing NW_####### doesn't couse any errors and I can see my aligned sequences. Error occures both on linux and windows.

**Comment by jrobinso** [comment] 2020-06-04 04:41
This should be fixed with release 2.8.3

**Closed by jrobinso** 2020-06-04 04:41 UTC
