### ISSUE TITLE
Recurring error messages on removing Gencode track

### ISSUE THREAD

**Issue by hchetia** [igvteam/igv#895] opened 2021-01-28 16:25 UTC
I have a saved session with few bw files and gencode v 24. Whenever i load the session and remove the gencode track. IGV goes frozen with lots of error messages popping up. See snippets below. I am running IGV 2.8.13 on macos big sur with 8 gb mem. (my mac has 32 gb ram).
Please help.

**Comment by hchetia** [comment] 2021-01-28 16:26
![image](https://user-images.githubusercontent.com/64626735/106167796-97b3e700-615b-11eb-98eb-8135c5213378.png)

**Comment by hchetia** [comment] 2021-01-28 16:28
![image](https://user-images.githubusercontent.com/64626735/106168116-ee212580-615b-11eb-9b9d-356020eca9f1.png)

**Comment by hchetia** [comment] 2021-01-28 16:41
![image](https://user-images.githubusercontent.com/64626735/106169793-c206a400-615d-11eb-85da-9562c9a96897.png)

**Comment by jrobinso** [comment] 2021-01-30 00:02
That looks pretty nasty.   If you can share the session please do.

**Comment by jrobinso** [comment] 2021-01-30 00:03
Also, the complete log not just a screenshot of contents,  there isn't enough visible on the screenshot to pinpoint a cause.  The "igv.log" file is in the "igv" folder in your home directory.

**Comment by hchetia** [comment] 2021-01-30 01:20
**Sharing the error log below-**
[igv:igv-1.log](https://github.com/igvteam/igv/files/5897114/igv.igv-1.log)

**Comment by jrobinso** [comment] 2021-01-30 04:49
Thanks.  The log is unfortunately not informative, and I can't reproduce
the behavior, but there's a chance its fixed in the upcoming 2.9 release,
which is available now as the snapshot build:
https://software.broadinstitute.org/software/igv/download_snapshot.   Note
there is no Mac package for this build, but it can be run from the command
line package.  Version 2.9 will be released next week.

If you can provide a session file that I can use to reproduce this that
would be helpful.

**Comment by hchetia** [comment] 2021-01-31 02:48
Hi, thanks for your reply. I am attaching a session file here.
I also shared the first error message triggered with gencode24 removal below.
![image](https://user-images.githubusercontent.com/64626735/106373108-5e8a9b00-6344-11eb-859d-012b8aa4e400.png)
![image](https://user-images.githubusercontent.com/64626735/106373157-b7f2ca00-6344-11eb-96a7-de66d9c7b60b.png)

[draft_github.xml.zip](https://github.com/igvteam/igv/files/5899101/draft_github.xml.zip)

**Comment by hchetia** [comment] 2021-01-31 02:59
I downloaded IGV Snapshot and tried the draft_github.xml.zip file. I got the same error from it too (See log).
**Using system JDK.
WARNING: package com.sun.java.swing.plaf.windows not in java.desktop
WARNING: package sun.awt.windows not in java.desktop
java version "14" 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
WARN [2021-01-30T21:53:57,146]  [Globals.java:135] [main]  Development mode is enabled
INFO [2021-01-30T21:53:57,163]  [DirectoryManager.java:181] [main]  IGV Directory: /Users/hc/igv
INFO [2021-01-30T21:53:57,795]  [Main.java:205] [AWT-EventQueue-0]  Startup  IGV Version snapshot 01/29/2021 11:18 PM
INFO [2021-01-30T21:53:57,800]  [Main.java:206] [AWT-EventQueue-0]  Java 14 (build 14+36-1461) 2020-03-17
INFO [2021-01-30T21:53:57,800]  [Main.java:209] [AWT-EventQueue-0]  Java Vendor: Oracle Corporation https://java.oracle.com/
INFO [2021-01-30T21:53:57,801]  [Main.java:211] [AWT-EventQueue-0]  JVM: Java HotSpot(TM) 64-Bit Server VM    
INFO [2021-01-30T21:53:57,801]  [DirectoryManager.java:86] [AWT-EventQueue-0]  Fetching user directory... 
INFO [2021-01-30T21:53:59,331]  [Main.java:214] [AWT-EventQueue-0]  Default User Directory: /Users/hc
INFO [2021-01-30T21:53:59,331]  [Main.java:215] [AWT-EventQueue-0]  OS: Mac OS X 10.16 x86_64
INFO [2021-01-30T21:54:00,743]  [GenomeManager.java:183] [pool-3-thread-1]  Loading genome: /Users/hc/igv/genomes/hg38.genome
INFO [2021-01-30T21:54:04,835]  [GenomeManager.java:224] [pool-3-thread-1]  Genome loaded.  id= hg38
INFO [2021-01-30T21:54:04,844]  [CommandListener.java:121] [Thread-4]  Listening on port 60151
INFO [2021-01-30T21:54:25,240]  [TrackLoader.java:122] [Thread-5]  Loading resource, path https://s3.amazonaws.com/igv.broadinstitute.org/data/hg38/gencode.v24.annotation.sorted.gtf.gz
INFO [2021-01-30T21:54:25,995]  [HttpUtils.java:961] [Thread-5]  Range-byte request succeeded
INFO [2021-01-30T21:55:01,251]  [TrackLoader.java:122] [Thread-6]  Loading resource, path https://s3.amazonaws.com/igv.broadinstitute.org/data/hg38/gencode.v24.annotation.sorted.gtf.gz
INFO [2021-01-30T21:55:09,204]  [MessageUtils.java:76] [pool-2-thread-3]  Error loading features for interval: chr5:167322068-167954210 <br>java.lang.NullPointerException
INFO [2021-01-30T21:55:09,805]  [MessageUtils.java:76] [pool-2-thread-5]  Error loading features for interval: chr8:96259901-96338995 <br>java.lang.NullPointerException
INFO [2021-01-30T21:55:11,030]  [MessageUtils.java:76] [pool-2-thread-2]  Error loading features for interval: chr14:105207285-105317577 <br>java.lang.NullPointerException
INFO [2021-01-30T21:55:12,537]  [MessageUtils.java:76] [pool-2-thread-1]  Error loading features for interval: chr8:131902092-132015642 <br>java.lang.NullPointerException
INFO [2021-01-30T21:55:13,637]  [MessageUtils.java:76] [pool-2-thread-4]  Error loading features for interval: chr5:80652651-80878815 <br>java.lang.NullPointerException**

**Comment by jrobinso** [comment] 2021-02-01 06:34
Thanks for the session, it contained an important detail, you are using gene lists.   I can reproduce the problem in 2.8.13 with this session, but not in the development (snapshot) build.  It loads fine, and I can remove the gencode track without error.  Are there any other steps I should take?

**Comment by jrobinso** [comment] 2021-02-03 05:19
This should be fixed with release 2.9.0.   If not please reopen.   Note that we do not support Java 14,  I doubt that anything to do with this issue just noting it.   The "IGV with Java" options will install its own copy of Java 11.

**Closed by jrobinso** 2021-02-03 05:19 UTC
