### ISSUE TITLE
Inability of Viewing Only Soft-clipped Reads

### ISSUE THREAD

**Issue by DarioS** [igvteam/igv#852] opened 2020-10-03 14:00 UTC
I am looking at whole genome sequencing DNA data and interested in insertions such as LINE1 retrotransposons or viruses. I would like to have a way to get rid of all of the reads which do not have soft-clipped segments, to be left with only the reads that do. I ticked the Show Soft-clipped Bases box in Preferences to get view shown below, but I'd like to only show the reads with an insertion. So, I'm after some kind of Hide Ordinary Reads option to tick in some preferences panel.

![image](https://user-images.githubusercontent.com/631218/94993048-8e61a600-05d1-11eb-8833-3269f2b6fdd8.png)

**Comment by jrobinso** [comment] 2020-10-05 23:53
What's an ordinary read?  That's going to have a different definition depending on what you are after.   In your case I am inferring that you want to only see reads with soft clips.    We should think about some more general kind of filter with options.

In the meantime of course the workaround of course is to create another bam with only the soft-clipped reads, probably a 1 liner with samtools.

**Comment by jrobinso** [comment] 2021-01-10 03:39
Apologies for the delay on this, Would this work for defining a "not ordinary" read?  Or perhaps we should call it "chimeric" reads?   The menu option would keep only reads with at least one of the following,

Soft clips
Split read (is or has supplementary alignments)
Not proper pair

**Comment by jrobinso** [comment] 2021-01-10 03:40
Also, this sort of filtering could be implemented at the loading or display level.    If implemented during loading reads not passing the filter are just discarded, potentially saving a lot of memory.    If implemented at the display level (right-click menu) you can toggle back and forth.

**Comment by DarioS** [comment] 2021-01-10 07:00
Yes, I would expect soft-clipped, split and improper pairs to appear. I hadn't thought of before and after alignment loading, but both of those options would be useful in different scenarios.

**Comment by jrobinso** [comment] 2021-01-10 17:24
Suggestions for naming the option.      "Group by ????"

**Comment by DarioS** [comment] 2021-01-10 20:00
I have no good suggestions, but the best which I can think of is Reference Agreeability. All of the reads I am interested in viewing and would be highlighted by the new option suggest some disagreement with the reference genome: an insertion of a retrotransposon or virus, a large human DNA deletion, or chromosomal translocation.

**Comment by jrobinso** [comment] 2021-01-11 03:57
Well, alignments with snps also disagree with the reference.   I'm not happy with it but as a working name I called it "group by > structural variant evidence".   Hopefully I come up with something better before release.   I added "group by" first because its trivial to do.   By coincidence I'm on a side project looking for SVs and this is useful,  I had written some python to extract these reads into a separate bam but its useful to see them together with the "normal" reads.  

Specifically what gets group is any read with "isProperPair == false",  presence of a soft clip, or marked supplementary.   The latter should not be needed, all split reads should have soft clips unless I'm missing something.

To see how complex this could get,  I'm not interested in "not proper pairs" unless the mate is mapped.   Also I'm not interested in reads with soft clips on both ends.   But for now I've kept it simple and use the more inclusive rule stated above.

I noticed the groups aren't labeled,  I thought they were, looking into that now.

**Comment by malcook** [comment] 2021-01-12 19:53
> In the meantime of course the workaround of course is to create another bam with only the soft-clipped reads, probably a 1 liner with samtools.

Another workaround would be to rewrite the bam file (again, probably a one-liner) with a new custom tag encoding the **class** of the alignment, in @DarioS 's case, based on a regex match to the cigar-line.  Then IGV's `group-by > tag` could be used to focus on soft-clipped alignments.

**Comment by jrobinso** [comment] 2021-01-12 20:57
@malcook Yes of course you could do that, but its cumbersome particularly with the 300 GB bams I'm working with now.   I added the "group by > structural variant evidence" option,  but before release I really hope to come up with a better name.  Ideally the name shouldn't interpret, might by SV might not,  maybe "group by > reference agreeability" is better.

**Comment by malcook** [comment] 2021-01-13 03:21
I'm unsure at this point whose use case is driving these requirements, yours or @DarioS 's but, brainstorming here, ...

perhaps something like "group by > named formula > ..." might be generic and useful for other purposes, where-in various formula's could be defined by user in some language (javascript? perl?) and evaluated for each alignment in an environment where the alignment's attributes and tag values were set.  The value of evaluating the formula would provide the grouping variable.

I've in the past wish I could group by formulas such as:
- NH==1 # is unique mapper 
- NM<4 
- CIGAR ~= /^\dS/ || CIGAR ~= /\dS$/ # is soft clipped

**Comment by jrobinso** [comment] 2021-01-13 17:40
The purpose of the feature, in essence, to segregate alignments that have some evidence of a change to the reference, not a snp but a structural change.    I think that describes both @DarioS and my use case, and is a fairly generic one.  

A language for this would be nifty but very time consuming to develop, and is not going to happen in my lifetime unless I get a pull request.   Only a tiny fraction of users would use it and I have about 50 open issues here, and another 50 in igv.js,  each of which impacts a much larger group.

**Comment by jrobinso** [comment] 2021-01-27 16:23
ok the option shall be called "reference concordance"

**Comment by malcook** [comment] 2021-01-27 17:06
to double-check on this topic.... is there currenlty any way to sort/group/filter alignments based on presence/extent or any aspect of soft-clipping and/or the CIGAR line?  Thanks!

**Comment by jrobinso** [comment] 2021-01-27 17:30
@malcook I am having a hard time parsing your question, to repeat this option groups alignments according to "reference concordance".  Discordant alignments are defined as any alignment with one or more of the following.  In practice the second is redundant as all split reads should also have soft clips

Soft clips
Split read (is or has supplementary alignments)
Not proper pair

**Comment by malcook** [comment] 2021-01-27 18:01
apologies... you parsed my question perfectly... it is my hasty posting you can't control.  ;)

I just tried it in nightly and it works great and is immediately useful to me. 

(though nightly continues in my hands to display complete path to file in the track label).

**Comment by jrobinso** [comment] 2021-01-27 18:06
@malcook did you send me a reproducible case I can use to see the complete path problem?

**Comment by jrobinso** [comment] 2021-01-27 18:20
@malcook Never mind, I found it.  Well I see a different problem, no sample name for the track (just filename).   I will fix this, maybe it will also fix your issue but I will be asking you to verify.

![Screen Shot 2021-01-27 at 10 17 58 AM](https://user-images.githubusercontent.com/933148/106035741-4d623580-6089-11eb-9703-e3665c345d64.png)

**Comment by jrobinso** [comment] 2021-02-03 05:24
This is now released as option "group by > reference concordance"

**Closed by jrobinso** 2021-02-03 05:24 UTC

**Comment by malcook** [comment] 2021-03-17 17:52
> A language for this would be nifty but very time consuming to develop, and is not going to happen in my lifetime unless I get a pull request.

FWIW: the new htslib [general filtering syntax for alignment records in SAM/BAM/CRAM readers](https://github.com/samtools/htslib/releases/tag/1.12) appears to now implement the needed language which would "merely" now need to be exposed from "IGV > Alignment Track > {Group, Sort, Color} by > expression" 

Do you agree @jrobinso ?

**Comment by jrobinso** [comment] 2021-03-17 22:11
@malcook I look forward to your pull request :)

IGV does not use htslib, so there is nothing to expose.
