### ISSUE TITLE
Data Range does not permit Max = 0

### ISSUE THREAD

**Issue by manschmi** [igvteam/igv#517] opened 2018-03-09 09:28 UTC
Manually setting Data Range would not allow to set Max for 0 but rather resets to 1.4E-45. The reason this would be nice to have this at 0 is for displaying stranded tracks with watson and crick data as plus and minus values. I could achieve the correct behavior using 'Overlay track', however since Overlay tracks are bit more tricky to work with and have less features, the simply ability to set Max to 0 would be good to have.

**Comment by jrobinso** [comment] 2018-03-14 21:12
OK, that would be a bug, it should let you do that for the reason you outline.   Could you confirm what version of IGV you encountered this with?

**Comment by manschmi** [comment] 2018-03-16 12:45
just checked with v2.3.91 and v2.4.9 (on MacOS 10.12.6 running java 1.6.0_65). Both behave that way.

**Comment by jrobinso** [comment] 2018-03-21 00:34
I've reproduced this and am working on it.   However,  from a practical point of view 1.4e-45 is very close to zero,  in the end it will look the same.

**Comment by jrobinso** [comment] 2018-03-21 05:20
This is fixed in 2.4.10

**Closed by jrobinso** 2018-03-21 05:20 UTC

**Comment by jrobinso** [comment] 2018-03-27 02:05
That was fixed with 2.4.10.
