### ISSUE TITLE
Intron view problem in v2.17.0

### ISSUE THREAD

**Issue by huangnengCSU** [igvteam/igv#1470] opened 2024-01-21 17:28 UTC
Hi,

There may be a problem of showing the intron region. I will show the screen shot of the IGV loading the same bam file in v2.16.2 and v2.17.0.
Thanks

![2 17](https://github.com/igvteam/igv/assets/28866823/f0e1bbc2-a504-4bac-aee8-02c16ef6ed5b)
![2 16 2](https://github.com/igvteam/igv/assets/28866823/57bbebe2-9283-4740-b470-eca1f01ca43f)

**Comment by jrobinso** [comment] 2024-01-21 20:57
I can't determine what I am looking at from the screenshots.     Are you highlighting the same reads?   What exactly do you mean by "Intron", what type of data is this (dna, rna, 3rd gene?),  and what display options and alignment preferences to do you enabled?

To investigate this I would need the data.   You can extract this portion by right-clicking, then select "Export Alignments..."  from the menu.  Zip the exported "sam" file and either attach it here, or if it is sensitive data  email us at igv-team@broadinstitute.org and I can send you a secure dropbox link.

**Comment by jrobinso** [comment] 2024-01-22 00:35
BTW it looks like you have "view as pairs" on in the 2.16.2 screenshot, and do not in the upper screenshot.   If that's not the case take a screenshot of the alignment menu for each case, so I can determine what you have set.

**Comment by huangnengCSU** [comment] 2024-01-22 17:14
The dataset is PacBio long reads RNA seq of WTC11 chromosome 19. I did not find the option of view as pairs.
Version: 2.17.0 and 2.16.0
![2 17 0](https://github.com/igvteam/igv/assets/28866823/f26d9ea1-8a37-4467-80fd-47c59f6e0dec)
![2 16 0](https://github.com/igvteam/igv/assets/28866823/73f4c09d-8060-4cdf-b192-ecfa2ab1f163)

**Comment by jrobinso** [comment] 2024-01-22 17:20
You can extract that data as instructed previously.

**Comment by huangnengCSU** [comment] 2024-01-22 17:38
Here is the data and the region is chr19:32,583,714-32,584,742. Thanks!

[visibleData.sam.zip](https://github.com/igvteam/igv/files/14013544/visibleData.sam.zip)

**Comment by huangnengCSU** [comment] 2024-01-22 17:46
You may also reproduce the problem in #1468 with this data. Thanks a lot.

**Comment by jrobinso** [comment] 2024-01-22 17:56
Thanks for the data, I can reproduce both.   It must be related to long-read RNA seq, which is an unusual combination we haven't tested.   Details like this are important, not much can be gleaned from a couple of screenshots.   I'll update here when the problem is found.

**Comment by huangnengCSU** [comment] 2024-01-22 18:09
Thanks, 2.17 has a lot of new content, looking forward to this version

**Comment by jrobinso** [comment] 2024-01-26 00:30
This is now fixed with release 2.17.1

**Closed by jrobinso** 2024-01-26 00:30 UTC
