### ISSUE TITLE
"Unexpected error repainting view. See igv.log for details" error message

### ISSUE THREAD

**Issue by ubuntolog** [igvteam/igv#1488] opened 2024-02-08 15:19 UTC
The above mentioned error message pops up constantly after loading a sample. 
![unnamed](https://github.com/igvteam/igv/assets/5293569/dcd17b5b-d76b-4807-a068-d8a7bab427cb)

I also noticed a visible rendering problem
![unnamed](https://github.com/igvteam/igv/assets/5293569/e2f95c9f-32fd-4ab0-a62e-c8a5d980fde3)

I found this in the log file
```
SEVERE [Feb 02,2024 09:29] [DataPanel] Error painting DataPanel
SEVERE [Feb 02,2024 09:29] [DataPanel] java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
                at org.igv/org.broad.igv.sam.AlignmentRenderer.drawAlignment(AlignmentRenderer.java:712)
                at org.igv/org.broad.igv.sam.AlignmentRenderer.drawPairedAlignment(AlignmentRenderer.java:509)
                at org.igv/org.broad.igv.sam.AlignmentRenderer.renderAlignments(AlignmentRenderer.java:363)
                at org.igv/org.broad.igv.sam.AlignmentTrack.renderAlignments(AlignmentTrack.java:655)
                at org.igv/org.broad.igv.sam.AlignmentTrack.render(AlignmentTrack.java:555)
                at org.igv/org.broad.igv.ui.panel.DataPanelPainter.draw(DataPanelPainter.java:236)
                at org.igv/org.broad.igv.ui.panel.DataPanelPainter.paintFrame(DataPanelPainter.java:177)
                at org.igv/org.broad.igv.ui.panel.DataPanelPainter.paint(DataPanelPainter.java:111)
                at org.igv/org.broad.igv.ui.panel.DataPanel.paintComponent(DataPanel.java:151)
                at java.desktop/javax.swing.JComponent.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
                at org.igv/org.broad.igv.ui.panel.DataPanelContainer.paintChildren(DataPanelContainer.java:155)
                at java.desktop/javax.swing.JComponent.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
                at java.desktop/javax.swing.JComponent.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
                at java.desktop/javax.swing.JComponent.paint(Unknown Source)
                at java.desktop/javax.swing.JViewport.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
                at java.desktop/javax.swing.JComponent.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
                at java.desktop/javax.swing.JComponent.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
                at java.desktop/javax.swing.JComponent.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
                at java.desktop/javax.swing.JComponent.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
                at java.desktop/javax.swing.JComponent.paint(Unknown Source)
                at java.desktop/javax.swing.JLayeredPane.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintChildren(Unknown Source)
                at java.desktop/javax.swing.JComponent.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintToOffscreen(Unknown Source)
                at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(Unknown Source)
                at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
                at java.desktop/javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
                at java.desktop/javax.swing.RepaintManager.paint(Unknown Source)
                at java.desktop/javax.swing.JComponent._paintImmediately(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
                at java.desktop/javax.swing.JComponent.paintImmediately(Unknown Source)
                at org.igv/org.broad.igv.ui.IGV.lambda$repaint$14(IGV.java:2248)
                at org.igv/org.broad.igv.ui.util.UIUtilities.invokeAndWaitOnEventThread(UIUtilities.java:166)
                at org.igv/org.broad.igv.ui.IGV.repaint(IGV.java:2235)
                at org.igv/org.broad.igv.ui.IGV.repaint(IGV.java:2225)
                at org.igv/org.broad.igv.ui.IGV.repaint(IGV.java:2209)
                at org.igv/org.broad.igv.batch.CommandExecutor.execute(CommandExecutor.java:250)
                at org.igv/org.broad.igv.batch.CommandListener.lambda$processClientSession$0(CommandListener.java:269)
                at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
                at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
                at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
                at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
                at java.base/java.security.AccessController.doPrivileged(Unknown Source)
                at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
                at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
                at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
                at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
                at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
                at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
                at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
                at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```
RNA samples are displayed correctly (no error messages).
The issue appeared in the version 2.17.1
Version 2.17.0 worked as expected

**Comment by jrobinso** [comment] 2024-02-08 17:20
Thanks for the report.  I can reproduce and have fixed the "unexpected error" issue, however I can't reproduce the rendering issue.  It might have been a side effect of the error.

**Comment by jrobinso** [comment] 2024-02-09 05:49
The fix for "Unexpected error repainting view" has been released with 2.17.2.   If the rendering error recurs please open another ticket with enough details to hopefully reproduce.  Thanks.

**Closed by jrobinso** 2024-02-09 05:49 UTC

**Comment by ubuntolog** [comment] 2024-02-09 08:23
Thank you. I will let you know, if the rendering issue persists

**Comment by lolhangman** [comment] 2024-03-13 08:34
Hello we have the same issue on a windows machine using package IGV 2.17.3 java included

**Comment by jrobinso** [comment] 2024-03-13 14:41
@lolhangman Please include the error trace from the igv.log contents as @ubuntolog did, along with steps to reproduce.

**Comment by helgathorv** [comment] 2024-03-13 17:02
@lolhangman You may have run into a problem that @jrobinso has already fixed but has not been released. Can you try the snapshot build at https://igv.org/doc/desktop/#DownloadSnapshot/ and let us know if that fixes it for you. If not, please provide the log and steps to reproduce.

**Comment by ubuntolog** [comment] 2024-03-14 14:35
I briefly tested 2.17.3 and did not see the bug. We are planning to switch to 2.17.3 soon. At the moment we are still using a snapshot version (built immediately after closing this issue) .

**Comment by lolhangman** [comment] 2024-03-14 14:52
Thank you for your help.
Unfortunately I don't have the logs as it was not on my computer but I asked the person to test the snapshot version you gave us.
I'll let you know the result asap

**Comment by jrobinso** [comment] 2024-03-14 16:52
OK, the error message is a generic one and is not enough for us to diagnose the problem.
