### ISSUE TITLE
Generic OAuth support

### ISSUE THREAD

**Issue by mbockol** [igvteam/igv#328] opened 2016-10-20 22:18 UTC
Hi All,

My institution supports oAuth for federated authentication and single sign on.  We'll be serving sequence data and igv-session.xml files under an Apache httpd server protected under that oAuth authentication. We'd like our users to be able to download the session files from the website, then load them in the IGV client.  Ideally their login to the website would follow through to IGV so they wouldn't need to supply credentials twice, but even if they did, that would be fine.  I'm wondering what would need to be changed in IGV to support non-Google oAuth providers? I'm new to oAuth in general, so my apologies if my description doesn't quite fit the ground truth.  Thanks for any suggestions you can provide. 

Matt

**Comment by jrobinso** [comment] 2016-11-14 22:06
Hi,  sorry for the delay,  I thought I had responded but don't see it here.  Perhaps its on igv-help, check your email there.

In brief,  could you be precise on the oAuth version (1 or 2).   It should be straightforward but let's start with the version,  then I can send more detailed questions.

**Comment by mbockol** [comment] 2016-11-18 17:42
Hi Jim,

Thanks for getting back to me. We’re running oAuth v2 through Microsoft ADFS.  My understanding from the team that manages the system here is that the login step requires using a web browser. I’ve never seen how IGV handles oAuth2 logins – does it launch a browser to get the token or is the login handled through IGV directly?  The oAuth team here seems to think that our infrastructure won’t support logins without a browser step.

Thanks,
Matt

**Comment by jrobinso** [comment] 2016-11-18 18:26
To see how IGV does oAuth login open "View > Preferences" and check Enable
Google Access.  Then select "Google > Login".    A browser will open asking
you to grant access.   The redirect URI is then
http://localhost:60151/oauthCallback,  which is actually IGV itself (IGV is
listening on port 60151).    IGV parses the token from this redirect.

This is used by a number of genomics projects hosted by Google.    Its
standard oAuth v2.   Unless you are doing something custom or out-of-spec
it would work,  but I would need to add a means to set the oauth urls,
scopes, and properties.   They are currently hardcoded for Google.   This
would not be difficult.    If we get to that point we could continue via
private email.

**Comment by mbockol** [comment] 2016-11-18 19:56
Ah, that makes sense. I think that should be fine with our infrastructure. At least, that would get past the first hurdle anyway ☺ Please let me know what questions I should be putting to our oAuth team and I’ll see what they come back with. If there’s a better email address to write to please let me know.

Thanks,
Matt

**Comment by jrobinso** [comment] 2016-11-18 20:44
There is some basic oAuth info here, and many other places:  https://aaronparecki.com/2012/07/29/2/oauth2-simplified#browser-based-apps

The link above pretty much covers it.  IGV is a "browser" type app in this context (desktop == browser).   As such it will use client_id and not a client secret.   See the "Browser-Based Apps" section.   So you will register IGV on your service, as described there.  IGV will need to know to the following, at a minimum:  

Authorization server URI,  oauth2server.com/auth  in the examples
client_id for IGV
scope, if you use scopes

That's it.   To get this information IGV will use a url, which your users will need to set in the IGV preferences, which should return a simple json object with the info.   Since you are potentially the first non-google oAuth user it would make things smoother if you can create a test account for my use.  You can use our igvteam (at) broadinstitute.org to communicate any confidential information.

**Comment by david-w-mead** [comment] 2017-01-09 17:19
Hi Jim,

I work with Matt and have been working on implementing the oauth service at our institution. We have things working now and I would like to talk with you about testing with the igv app. I have tried the email above (igvteam (at) broadinstitute.org) and am getting by email bounced back. Is there another email I can use to contact you with info you would need to testing against our oauth?

Thanks,

David

**Comment by jrobinso** [comment] 2017-01-09 17:35
Hi David, sorry the email is  igv-team, note the dash, apologies if I gave you the wrong address.  In any event this is the best place for discussions unless you need to send sensitive information.

OAuth has only been used, so far, with google, give me a day to review this and see what is needed to support another service.   In the meantime you should be able to get it to work by adding the following to your track configuration

   headers: {"Authorization": accessToken}

where accessToken is the value of the access token.   You can pass any arbitrary header to your server in this way.    Please give that a try and let me know the result, because any development on my end will be premised on that.  This is how we interact with google servers (passing the access token).

**Comment by jrobinso** [comment] 2017-01-09 23:13
Got the info, and apologies my previous response would apply to igv.js,  not igv desktop.  I deleted it to avoid confusing others.

**Comment by holtgrewe** [comment] 2017-06-13 11:46
@david-w-mead This sounds very interesting to me as well! Did you have to modify the IGV source code or did it work out of the docs following Jim's guide?

**Comment by jrobinso** [comment] 2017-06-13 15:58
@holtgrewe  Generic oAuth has been implemented by David, but not documented yet.   Apologies for that I have a backlog of doc tasks for the 3.0 release.  The PRs are https://github.com/igvteam/igv/pull/400, https://github.com/igvteam/igv/pull/401, and https://github.com/igvteam/igv/pull/415

**Comment by david-w-mead** [comment] 2017-06-13 17:17
I had to modify the code. I was working to make this work with Microsoft’s Oauth2 implementation (Through Azure Active Directory) and there were differences between this and Google’s implementation that I had to code around. I’m not certain how this work with other oauth2 implementations.

- David

**Comment by jrobinso** [comment] 2017-06-13 17:23
Yes I should modify my characterization to "believed to be generic",  the only providers we have tested against are Google and Microsoft/Azure.

**Comment by holtgrewe** [comment] 2017-07-12 19:04
Hi Jim, I'm having a hard time making IGV 3.0 (from git tag `v3.0`) talk to our local RedHat Keycloak v3.2.0 instance. I "reverse-engineered" the `oauth-config.json` format but am stuck after IGV tries to refresh the token directly after login and fails in this. I would dearly like to make this work...

I have some logs that I have trouble pinpointing the problem in but don't want to post them in full here.

Could you help me with this?

**Comment by jrobinso** [comment] 2017-07-12 19:20
Yes, contact me offline jrobinso      ucsd.edu

**Comment by holtgrewe** [comment] 2017-07-13 11:13
Ah, nothing better than debugging distributed systems. I have found the culprit! In `OAuthUtils.java`, the profile fetching fails (of course, I authenticate to my own OAuth provider and not Google). The exception is handled above and this makes the HTTP callback fail and not properly process the tokens.

Below a minimal fix for my setting, nothing final, I guess.

To reproduce, just throw an IOException and you should see the same behaviour as I am.

BTW: it would be nice if I could put the realm information (instead of "Google", I'd like to have "ACME.ORG" fo rexample) in the `oauth-config.json`. Once I'm done with my tinkering here, I'll put up a Wiki page on how to setup IGV+Keycloak+Apache for self-hosted, secure SSO-based IGV file viewing here in the Wiki if you think this is a good idea.

```
diff --git a/src/org/broad/igv/ga4gh/OAuthUtils.java b/src/org/broad/igv/ga4gh/OAuthUtils.java
index 20daa03..cfab41e 100644
--- a/src/org/broad/igv/ga4gh/OAuthUtils.java
+++ b/src/org/broad/igv/ga4gh/OAuthUtils.java
@@ -232,15 +249,21 @@ public class OAuthUtils {
         }
     }
 
-    private void fetchUserProfile() throws IOException {
-
+    private void fetchUserProfile() {
+      try {
         if (clientId == null) fetchOauthProperties();
 
+        System.err.println("Fetching user profile...");
+
         URL url = new URL("https://www.googleapis.com/plus/v1/people/me?access_token=" + accessToken);
         String response = HttpUtils.getInstance().getContentsAsJSON(url);
         JsonParser parser = new JsonParser();
         JsonObject obj = parser.parse(response).getAsJsonObject();
         currentUserName = obj.get("displayName").getAsString();
+      } catch (IOException e) {
+        System.err.println("Problem fetching user profile");
+        e.printStackTrace();
+      }
     }

```

**Comment by jrobinso** [comment] 2017-07-14 05:09
OK, thanks for the debugging.   To be honest this feature (generic oAuth) has not received a lot of attention.   I'll leave this open and tag it with a label so it gets some priority.

**Comment by holtgrewe** [comment] 2017-07-14 05:18
Would you accept a PR for 3.0 release with some cosmetic changes such as the label coming from configuration and configuration being in the UI?

BTW what's the eta for 3.0?

**Comment by jrobinso** [comment] 2017-07-14 06:27
Yes, subject to review of course.   The trickiest aspect of these oAuth PRs
is testing as I don't have a means to test any provider other than Google.


Most of the feature set currently known as "3.0" will be released soon,
within weeks, but as "2.4".    Some planned features for 3.0 are just
getting started and we don't want to hold the 3rd gen (pacbio) and Cram
support features hostage any longer.   So what is currently the "3.0"
branch will become, effectively, the 2.4 release.

On Thu, Jul 13, 2017 at 10:18 PM, Manuel Holtgrewe <notifications@github.com

**Closed** 2018-10-25 20:54 UTC
