### ISSUE TITLE
IGV release notes UserGuide links are 404 

### ISSUE THREAD

**Issue by malcook** [igvteam/igv#1466] opened 2024-01-06 13:56 UTC
The UserGuide links in [2.17.x - IGV Desktop Application](https://igv.org/doc/desktop/#ReleaseNotes/2.17.x/#igv-2170-jan-2023) are 404

example: 

https://igv.org/doc/desktop/#UserGuide/tracks/alignments/base_modifications/ 
is linked to as 
https://igv.org/UserGuide/tracks/alignments/base_modifications/

presumably they all need their prefix changed.

**Comment by jrobinso** [comment] 2024-01-06 16:54
Hi Malcolm,  I can't reproduce this.   Could you try clearing your cache?    I'm not sure that is the issue as there was no such page earlier to be cached, but at the moment on my Mac the links are correct.

**Comment by jrobinso** [comment] 2024-01-06 17:01
I'm looking at the page source,  it looks like these links are generated at runtime so it might depend on how you go to the page (the history of clicks).    That's unfortunate but its my best guess.

**Comment by helgathorv** [comment] 2024-01-06 17:59
Oops. Looks like my responses to this got lost. 

@jrobinso I beat you to it. I already deployed a fix a couple of hours ago.

@malcook Thanks for letting us know. It should be fixed now - let us know if you still have any issues (although as Jim said, you may have to clear your cache)

**Closed** 2024-01-06 22:54 UTC
