### ISSUE TITLE
Junctions track displayed even though switched off in settings

### ISSUE THREAD

**Issue by pd3** [igvteam/igv#1276] opened 2023-01-09 13:09 UTC
In the latest IGV v2.15.4 the junctions track is always displayed even though it's switched off in settings.

**Comment by jrobinso** [comment] 2023-01-09 17:31
I can't reproduce the error.  On which tab are you disabling junctions?  There are 3 tabs for alignment data, the generic "Alignments" tab,  then tabs specifically for RNA and 3rd gen.   The latter 2 are for overriding default ("Alignments") behavior.

**Comment by pd3** [comment] 2023-01-10 08:59
This was in the alignments tab and the data were short read exomes. The only unusual thing was that IGV was run in batch mode. In the RNA tab the junctions are turned off as well and in the 3rd gen tab I don't see that setting.

The config file reflected the setting for the generic tab
```
$ cat ~/igv/prefs.properties | grep JUNC
SAM.SHOW_JUNCTION_TRACK=false
```

I 've now tried on a different set of bams (as I cannot go easily back to the ones where I observed the problem originally) and it is working as expected now, i.e. no junctions track. I will comment here in case it happens again.

**Comment by jrobinso** [comment] 2023-01-10 18:17
The batch mode is a potentially important detail.   Are you running batch form the UI or starting up with a command line parameter?  If the latter, and if you are also doing preference overrides through the command line,  there could be a bug there.   But I would need some reliable steps to reproduce.   I'm closing this for now, reopen if you discover steps to reproduce.

**Closed by jrobinso** 2023-01-10 18:17 UTC

**Comment by jrobinso** [comment] 2023-01-11 17:38
If you can send a link to igvteam (at) broadinstitute.org and step-by-step instructions I'll look into it.   Also, sending your "prefs.properties" file in <user home>/igv might be important.
