### ISSUE TITLE
It does not load more than a track at time. Please help!

### ISSUE THREAD

**Issue by AndyAndy88** [igvteam/igv#1028] opened 2021-09-14 11:56 UTC
Hi everyone,

I am using IGV 2.11.0 (but I am experiencing this issue with all the other previous versions), on Windows with 16GB RAM.

1) The problem is that it does not load more than one track. If I try to load track A and track B, it only shows track A. Basically, after a loading phase, while track A appears, track B does not (and track height get blocked on 0-10,00) as you can see from the attached screenshot.
2) The problem does not depend on the nature of the track since I can open track B if I load it alone. Also, if I open a session where track A and B have been already loaded (by someone else for example) they both appear and all is normal.
3) I have same issues with every other tracks.

Yes, I checked on preferences and I set them as my colleagues (they have no problem). We are all working on the same type of machine and we have the same settings now. So it does not seems to be related to settings.

I tried on another spare laptop. I installed IGV and try to load few tracks: same problem! So it is not the machine. It seems to be something I do while installing.
All I can think of is Firewall access which the system ask me to allow the first time I run IGV (I confirmed it), but I am not sure..

Does someone have any ideas of why this happen?

Thank you,
Andrea
![Screen](https://user-images.githubusercontent.com/90694705/133253327-ff605aac-cc22-42c3-aac5-5bd88d80d057.JPG)

**Comment by AndyAndy88** [comment] 2021-09-15 07:47
Yes. Here you go.
Thank you!


[igv.log](https://github.com/igvteam/igv/files/7167901/igv.log)

**Comment by jrobinso** [comment] 2021-09-15 21:36
Still looking at this.  Could you give us your "prefs.properties" file, its located in the "igv" folder.

**Comment by jrobinso** [comment] 2021-09-15 21:44
Another question, do you have pre-computed coverage tracks for the bams you are trying to load?  The would be in the same folder as the bam, but have an extension ".tdf".

**Comment by jrobinso** [comment] 2021-10-05 16:57
I will assume this is fixed with the commit referenced above, in any event I can't reproduce it without more information.  The fix will be in release 2.11.2 coming out shortly.

**Closed by jrobinso** 2021-10-05 16:58 UTC
