### ISSUE TITLE
Permissions Error? "Error encountered querying alignments"

### ISSUE THREAD

**Issue by justinfinkle** [igvteam/igv#827] opened 2020-07-13 23:20 UTC
I get the following error when trying to look at a particular region in IGV. The error does not happen when loading IGV from the shell script (`IGV_2.8.6.app/Contents/MacOS/IGV`) which prompts for access. MacOS version `10.15.5`. 

Anyway to resolve the permissions for the app more broadly?

```
ERROR [2020-07-13T17:47:02,697] [AlignmentTileLoader.java:313]  Error loading alignment data
htsjdk.samtools.util.RuntimeIOException: /Users/justin.finkle/Desktop/test/test_bam.bam.bai (Operation not permitted)
	at htsjdk.samtools.MemoryMappedFileBuffer.<init>(MemoryMappedFileBuffer.java:28) ~[htsjdk-2.21.3.jar:?]
	at htsjdk.samtools.AbstractBAMFileIndex.<init>(AbstractBAMFileIndex.java:64) ~[htsjdk-2.21.3.jar:?]
	at htsjdk.samtools.DiskBasedBAMFileIndex.<init>(DiskBasedBAMFileIndex.java:46) ~[htsjdk-2.21.3.jar:?]
	at htsjdk.samtools.BAMFileReader.getIndex(BAMFileReader.java:419) ~[htsjdk-2.21.3.jar:?]
	at htsjdk.samtools.BAMFileReader.createIndexIterator(BAMFileReader.java:952) ~[htsjdk-2.21.3.jar:?]
	at htsjdk.samtools.BAMFileReader.query(BAMFileReader.java:612) ~[htsjdk-2.21.3.jar:?]
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:533) ~[htsjdk-2.21.3.jar:?]
	at htsjdk.samtools.SamReader$PrimitiveSamReaderToSamReaderAdapter.query(SamReader.java:538) ~[htsjdk-2.21.3.jar:?]
	at org.broad.igv.sam.reader.BAMReader.query(BAMReader.java:180) ~[igv.jar:?]
	at org.broad.igv.sam.AlignmentTileLoader.loadTile(AlignmentTileLoader.java:160) [igv.jar:?]
	at org.broad.igv.sam.AlignmentDataManager.loadInterval(AlignmentDataManager.java:405) [igv.jar:?]
	at org.broad.igv.sam.AlignmentDataManager.load(AlignmentDataManager.java:351) [igv.jar:?]
	at org.broad.igv.sam.CoverageTrack.load(CoverageTrack.java:175) [igv.jar:?]
	at org.broad.igv.ui.IGV.lambda$repaint$8(IGV.java:2388) [igv.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.FileNotFoundException: /Users/justin.finkle/Desktop/test/test_bam.bam.bai (Operation not permitted)
	at java.io.FileInputStream.open0(Native Method) ~[?:?]
	at java.io.FileInputStream.open(Unknown Source) ~[?:?]
	at java.io.FileInputStream.<init>(Unknown Source) ~[?:?]
	at htsjdk.samtools.MemoryMappedFileBuffer.<init>(MemoryMappedFileBuffer.java:21) ~[htsjdk-2.21.3.jar:?]
	... 17 more

**Comment by jrobinso** [comment] 2020-07-14 03:36
I thought I responded to this but I don't see it.   If there is a way we would like to know it.     Version 2.8.6 is notarized and signed (@davideby @helgathorv correct me if that is incorrect).   I think that's all we can do.   If the problem persists the workaround is to not use the privileged folders Downloads, Documents, or Desktop to store data, or alternatively start IGV from the command line.

**Comment by davideby** [comment] 2020-07-14 17:08
You have that correct @jrobinso, 2.8.6 is notarized.  @helgathorv and I had speculated there might be an issue in a case like this, where the file access to the BAM index is _implied_ rather than chosen directly by the user.  This seems to confirm it.

We're having similar issues in GSEA and I have an experimental fix in the works there to see if it improves things.  But if that fails - and *until then* in any case - you are correct about avoiding the privileged folders or using the command line.  Apple's recent changes are making this difficult, and they don't necessarily make the documentation on it clear.

**Comment by jrobinso** [comment] 2020-07-14 18:46
@davideby That would make sense.   It seems that with Catalina the user must select explicitly through the file dialog any file in Documents, Desktop, or Downloads.  Its similar to web browser's restrictions on file.   I suppose the idea is to keep applications from "fishing" for files,  which is in fact what we are doing.    I think the ultimate correct fix for this is to force the user to explicitly select the index file.   This is exactly what we do for the web application  (igv.js).

**Comment by jrobinso** [comment] 2020-07-15 04:37
OK, well now I'm stumped.  I can't reproduce this on my brand new Catalina Macbook Pro.  OS version 10.15.5.   I downloaded a bam and its index,  placed them on the Desktop,  loaded the Bam and zoomed into to load alignments. 

@justinfinkle If you get give us concrete steps to reproduce this we will look into it further.    Another thing you might try is to give IGV explicit access to Files and Folders.  You do this from System Preferences -> Security and Privacy.    I did not need to do that, and only a few apps have these privileges on my Mac, actually only 2 sshd and Sophos.

**Comment by jrobinso** [comment] 2020-07-17 04:27
@justinfinkle I'm closing this only to consolidate discussion of this in one issue (https://github.com/igvteam/igv/issues/829).

Loading from the shell script so far is the best and preferred solution.  We're trying to figure out why that works, but clicking on our bundled app icon does not.

**Closed** 2020-07-17 23:23 UTC
