### ISSUE TITLE
Failed to save sashimi plot svg

### ISSUE THREAD

**Issue by zhipengliux** [igvteam/igv#1295] opened 2023-03-07 06:41 UTC
IGV version is 2.16.0, but v2.13.2 to save sashimi.svg is successful.

**Comment by PINGPENG8** [comment] 2023-03-07 06:48
Additionally, V2.16.0 save sashimi.svg is 0kb, it's empty. And, i can't turn it off, it's stuck.

**Comment by jrobinso** [comment] 2023-03-09 04:48
I'm not able to reproduce your problem,  I will need more details.   Also I don't know what you mean by "i can't turn it off, its stuff".  Turn what off?

For a start, could you zip and attach your igv log file?  It will be in an "igv" folder under your home directory and have a name like "igv0.log".   That might be enough to identify the problem.

**Comment by h-joshi** [comment] 2023-10-10 05:47
Lab I'm working in is also having issues saving sashimi plot to SVG. Have tried this on
* Mac OS X Big Sur 11.7.10 / openjdk 11.0.11 2021-04-20 / IGV 2.6.11
* Windows 11 / IGV 2.6.12

Saving reads view to SVG works
However, saving sashimi plot (for the same view) does not

In both instances, the CPU usage skyrocketed, IGV hung and eventually when it does become response, we get a 0Kb SVG file.

**Comment by jrobinso** [comment] 2024-02-22 04:15
Apologies for the long delay on this.  I'm working on it now.  In my tests the culprit seems to be the annotation (gene) tracks, not the Sashimi plot per se.   I will try to solve that problem, but would it be useful to export the Sashimi plot alone, as an option?

**Comment by h-joshi** [comment] 2024-02-22 04:20
> Apologies for the long delay on this. I'm working on it now. In my tests the culprit seems to be the annotation (gene) tracks, not the Sashimi plot per se. I will try to solve that problem, but would it be useful to export the Sashimi plot alone, as an option?

Absolutely. Currently, we just take screenshots manually as a workaround.

**Comment by jrobinso** [comment] 2024-02-22 05:27
I found the issue, I think.  This should be fixed in the development snapshot build: https://igv.org/doc/desktop/#DownloadSnapshot/.  The fix will be included in the next point release.

**Closed** 2024-07-02 23:06 UTC
