### ISSUE TITLE
Lost access to google bucket(s)

### ISSUE THREAD

**Issue by chipstewart** [igvteam/igv#1262] opened 2022-11-19 19:45 UTC
Recently  I've lost ability to load files into igv  from a google  bucket  - despite having gcloud access to the bucket. Among my attempted fixes  was to  reboot, renew google project accces using gcloud init,  as well as gcloud auth login.   I also updated igv to Version 2.15.2 and renamed ~/igv so igv would start from scratch. From igv, clicked on "Enable Google Access" on the home preference page., then logged into google via the google/login menu - which seemed to work except when accessing files on google buckets.  

The igv log file has messages like this when failing to load a bam: 

SEVERE [Nov 19,2022 13:59] [IGV] Error loading track
SEVERE [Nov 19,2022 13:59] [IGV] org.broad.igv.exceptions.DataLoadException: An error occurred while accessing:    gs://fc-05f24b20-5597-41e1-ba23-e4652e4ce6f0/Shipp_Getz_IBM_DLBCL_286_WES_SV_Sep22/RP-707.PDO-28202.SM-MQXDW/Custom_Selection/STUDY00004951_URMC-412-DLBCL-RelBx01/v2/STUDY00004951_URMC-412-DLBCL-RelBx01.bam<br>Error loading BAM file: org.broad.igv.exceptions.DataLoadException: An error occurred while accessing:    gs://fc-05f24b20-5597-41e1-ba23-e4652e4ce6f0/Shipp_Getz_IBM_DLBCL_286_WES_SV_Sep22/RP-707.PDO-28202.SM-MQXDW/Custom_Selection/STUDY00004951_URMC-412-DLBCL-RelBx01/v2/STUDY00004951_URMC-412-DLBCL-RelBx01.bam.bai<br>Index file not found.  Tried <br>gs://fc-05f24b20-5597-41e1-ba23-e4652e4ce6f0/Shipp_Getz_IBM_DLBCL_286_WES_SV_Sep22/RP-707.PDO-28202.SM-MQXDW/Custom_Selection/STUDY00004951_URMC-412-DLBCL-RelBx01/v2/STUDY00004951_URMC-412-DLBCL-RelBx01.bam.bai<br>gs://fc-05f24b20-5597-41e1-ba23-e4652e4ce6f0/Shipp_Getz_IBM_DLBCL_286_WES_SV_Sep22/RP-707.PDO-28202.SM-MQXDW/Custom_Selection/STUDY00004951_URMC-412-DLBCL-RelBx01/v2/STUDY00004951_URMC-412-DLBCL-RelBx01.bai<br>gs://fc-05f24b20-5597-41e1-ba23-e4652e4ce6f0/Shipp_Getz_IBM_DLBCL_286_WES_SV_Sep22/RP-707.PDO-28202.SM-MQXDW/Custom_Selection/STUDY00004951_URMC-412-DLBCL-RelBx01/v2/STUDY00004951_URMC-412-DLBCL-RelBx01.bam.csi<br>gs://fc-05f24b20-5597-41e1-ba23-e4652e4ce6f0/Shipp_Getz_IBM_DLBCL_286_WES_SV_Sep22/RP-707.PDO-28202.SM-MQXDW/Custom_Selection/STUDY00004951_URMC-412-DLBCL-RelBx01/v2/STUDY00004951_URMC-412-DLBCL-RelBx01.csi
	at org.igv/org.broad.igv.track.TrackLoader.load(TrackLoader.java:272)
	at org.igv/org.broad.igv.ui.IGV.load(IGV.java:1249)
	at org.igv/org.broad.igv.ui.IGV.loadResources(IGV.java:1179)
	at org.igv/org.broad.igv.ui.IGV$2.run(IGV.java:409)
	at org.igv/org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

This is the result accessing a bam via gsutil (evidence I have access):

$ gsutil ls -lah  gs://fc-05f24b20-5597-41e1-ba23-e4652e4ce6f0/Shipp_Getz_IBM_DLBCL_286_WES_SV_Sep22/RP-707.PDO-28202.SM-MQXDW/Custom_Selection/STUDY00004951_URMC-412-DLBCL-RelBx01/v2/STUDY00004951_URMC-412-DLBCL-RelBx01.bam
 33.31 GiB  2022-09-20T16:47:13Z  gs://fc-05f24b20-5597-41e1-ba23-e4652e4ce6f0/Shipp_Getz_IBM_DLBCL_286_WES_SV_Sep22/RP-707.PDO-28202.SM-MQXDW/Custom_Selection/STUDY00004951_URMC-412-DLBCL-RelBx01/v2/STUDY00004951_URMC-412-DLBCL-RelBx01.bam#1663692433569878  metageneration=1
TOTAL: 1 objects, 35771464884 bytes (33.31 GiB)

$ gsutil ls -lah  gs://fc-05f24b20-5597-41e1-ba23-e4652e4ce6f0/Shipp_Getz_IBM_DLBCL_286_WES_SV_Sep22/RP-707.PDO-28202.SM-MQXDW/Custom_Selection/STUDY00004951_URMC-412-DLBCL-RelBx01/v2/STUDY00004951_URMC-412-DLBCL-RelBx01.bai
  5.96 MiB  2022-09-20T16:37:02Z  gs://fc-05f24b20-5597-41e1-ba23-e4652e4ce6f0/Shipp_Getz_IBM_DLBCL_286_WES_SV_Sep22/RP-707.PDO-28202.SM-MQXDW/Custom_Selection/STUDY00004951_URMC-412-DLBCL-RelBx01/v2/STUDY00004951_URMC-412-DLBCL-RelBx01.bai#1663691822628809  metageneration=1
TOTAL: 1 objects, 6246160 bytes (5.96 MiB)

I vaguely recall having this problem in the distant past (before the pandemic), but I 've  run out of things to try.

**Comment by jrobinso** [comment] 2022-11-19 21:45
It seems it thinks the index file isn't there, why that should be I can't tell from the stacktrace.   One possibility,  Google reports "not found" if you try to access a file you don't have access to.    I know you verified that, but if you have multiple Google accounts its possible you are logged into the wrong one in IGV.   Check the "Google" menu and logout if not sure.   I know because that just happened to me trying to reproduce your error.

Are you using "Load by URL"?   If so are you also entering the URL to the index?

**Comment by chipstewart** [comment] 2022-11-21 13:12
Thanks much for looking into this.  The account  I used to log into Google was/is my broad account  ( although I've been known to misspell "broadinstitute" on occasion - but not this occasion) and II also used "Load from URL..." to load file(s) from google buckets.   The number of times loading data from a google bucket has worked for me  over the past few years  must be in the thousands - I use IGV a lot.  This AM my first attempt to load a bam from a bucket failed again (same error message) but my second attempt succeeded!!- although I'm not sure which step was the key.  Perhaps it was the order (logout of google in igv, quit igv, gcloud init, start igv, login to google from igv, Load from URL... Voilà).

**Comment by jrobinso** [comment] 2022-11-21 16:19
I'll try various combinations to see if I can reproduce.    If you happen on the magic order to force this to happen let me know!

**Comment by chipstewart** [comment] 2022-11-25 14:56
This morning igv is again resistant to loading files from a google bucket - even after rebooting, and going through the ritual list of steps (logout of google in igv, quit igv, gcloud init, start igv, login to google from igv, Load from URL).  Access works ok via gsutil but not from igv. Here is the end of the igv.log from this morning: 

ERROR [2022-11-25T06:36:35,694] [IGV.java:1336]  Error loading track
org.broad.igv.exceptions.DataLoadException: An error occurred while accessing:    https://www.googleapis.com/storage/v1/b/fc-secure-66f5eeb9-27c4-4e5c-b9d6-0519aca5889d/o/submissions%2F293ef543-e28c-4090-a345-8d8aa15d2c46%2FRNABAMSortAndIndex%2Fcb042f03-8da3-4fa7-b3a2-30985ea23f09%2Fcall-samtools_sort_and_index%2Fattempt-2%2FCTSP-ACYZ-TTP1-A.samtools.bam?alt=media<br>Error loading BAM file: org.broad.igv.exceptions.HttpResponseException: Access forbidden <br> 
	at org.broad.igv.track.TrackLoader.load(TrackLoader.java:244) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.load(IGV.java:1401) ~[igv.jar:?]
	at org.broad.igv.ui.IGV.loadResources(IGV.java:1333) [igv.jar:?]
	at org.broad.igv.ui.IGV$4.run(IGV.java:474) [igv.jar:?]
	at org.broad.igv.util.LongRunningTask.call(LongRunningTask.java:72) [igv.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
INFO [2022-11-25T06:36:35,696] [MessageUtils.java:76]  Error loading https://www.googleapis.com/storage/v1/b/fc-secure-66f5eeb9-27c4-4e5c-b9d6-0519aca5889d/o/submissions%2F293ef543-e28c-4090-a345-8d8aa15d2c46%2FRNABAMSortAndIndex%2Fcb042f03-8da3-4fa7-b3a2-30985ea23f09%2Fcall-samtools_sort_and_index%2Fattempt-2%2FCTSP-ACYZ-TTP1-A.samtools.bam?alt=media: An error occurred while accessing:    https://www.googleapis.com/storage/v1/b/fc-secure-66f5eeb9-27c4-4e5c-b9d6-0519aca5889d/o/submissions%2F293ef543-e28c-4090-a345-8d8aa15d2c46%2FRNABAMSortAndIndex%2Fcb042f03-8da3-4fa7-b3a2-30985ea23f09%2Fcall-samtools_sort_and_index%2Fattempt-2%2FCTSP-ACYZ-TTP1-A.samtools.bam?alt=media<br>Error loading BAM file: org.broad.igv.exceptions.HttpResponseException: Access forbidden <br> 

same bam from gsutil - no access problem: 
$ gsutil ls -lah gs://fc-secure-66f5eeb9-27c4-4e5c-b9d6-0519aca5889d/submissions/293ef543-e28c-4090-a345-8d8aa15d2c46/RNABAMSortAndIndex/cb042f03-8da3-4fa7-b3a2-30985ea23f09/call-samtools_sort_and_index/attempt-2/CTSP-ACYZ-TTP1-A.samtools.bam
  8.08 GiB  2022-11-25T00:48:09Z  gs://fc-secure-66f5eeb9-27c4-4e5c-b9d6-0519aca5889d/submissions/293ef543-e28c-4090-a345-8d8aa15d2c46/RNABAMSortAndIndex/cb042f03-8da3-4fa7-b3a2-30985ea23f09/call-samtools_sort_and_index/attempt-2/CTSP-ACYZ-TTP1-A.samtools.bam#1669337289436762  metageneration=1
TOTAL: 1 objects, 8671462355 bytes (8.08 GiB)

Not sure who to ask about google authorization failures.

**Comment by jrobinso** [comment] 2022-11-25 18:00
I'm a bit stumped on this.   I can try creating a special IGV build with some more logging statements to see if we can narrow this down.   It will probably be Monday before I can have that ready.

Could you try loading your bam from https://igv.org/app,  by URL from the "Tracks" menu.     If it fails look at the console output in the browser, which you can enable from the "View" menu in Chrome.     If it doesn't fail that is also information.

**Comment by chipstewart** [comment] 2022-11-26 15:12
https://igv.org/app succeeded in displaying a bam from a google bucket using Chrome. Brave needed some cache cleaning and restarting to get it working as well. There was an extra "security key" dialog for  https://igv.org/app that the local igv app never required (not at all sure if that is relevant).  Thanks for suggesting this!

**Comment by jrobinso** [comment] 2022-11-28 04:01
Chip,  I am assuming these are not "Requestor Pays" buckets,  correct?

**Comment by jrobinso** [comment] 2022-11-28 05:05
I sent some instructions for running a special IGV build with extra logging statements to your broad email.  Reply here if you don't get it.

**Comment by chipstewart** [comment] 2022-11-28 09:08
Hi Jim - The bams/files were/are not in "Requestor Pays" buckets. Just data in terra workspace buckets where I have "owner" access.

**Comment by chipstewart** [comment] 2022-11-28 09:28
Followed instructions to download and run the special IGV build with extra logging statements.   Will send log files and stdout via email.  This special igv at this time in the AM had no problem loading and displaying the bams from the google bucket.  I didn't reboot or do any gcloud init anything - it just worked.   Is this google's way of  telling me to do my igving  at 4am ?

**Comment by jrobinso** [comment] 2022-11-28 16:27
@chipstewart  4 AM, yikes.  I don't know, probably a coincidence.   I think you indicated this is intermittent.   Just keep that build around for the next time it happens.

**Comment by jrobinso** [comment] 2022-11-28 16:28
Or is it still happening with the released IGV?

**Comment by chipstewart** [comment] 2022-11-29 02:44
At 940pm (18 hours later) the special igv and the relased igv 2.15.2 are both able to load bams from a google bucket!

**Comment by jrobinso** [comment] 2022-11-29 03:42
OK, that's good I guess.  I added even more log statements, if it happens again download a fresh copy from the same URL and give it a try.

**Comment by jrobinso** [comment] 2022-11-29 06:04
Closing for now, re-open when/if this recurrs.

**Closed by jrobinso** 2022-11-29 06:04 UTC

**Comment by chipstewart** [comment] 2022-12-01 02:29
Thanks

**Comment by jrobinso** [comment] 2024-06-23 06:29
@iglc We never resolved this in Chip's case as he could not reproduce it.   Below are the instructions I sent him, could you try this and post the results here, or send the igv log file to igv-team@broadinstitute.org

* From your "igv directory" delete or move all log files.    e.g.  rm *log*. or. mv *log* bak/.
* Download and unzip https://data.broadinstitute.org/igv/projects/downloads/chip/IGV_snapshot.zip
* Open a command terminal in the "IGV_snapshot" directory.
* Run the shell script.    "./igv.command"
* Try loading your gs bams
* Exit gracefully (from the File menu)
* Send me any resulting "log" files

**Comment by jrobinso** [comment] 2024-06-23 06:44
Oh instructions are for a mac, if you are on linux run ./igv.sh, and if on windows ./igv.bat
