### ISSUE TITLE
Read view cut off at bottom

### ISSUE THREAD

**Issue by gevro** [igvteam/igv#981] opened 2021-06-10 22:24 UTC
Hi, One of my CRAM files for some reason the viewing window for alignments seems to be cut off at the bottom and reads are definitely missing. It is only happening for this CRAM file.
<img width="1523" alt="Screen Shot 2021-06-10 at 6 23 12 PM" src="https://user-images.githubusercontent.com/47928628/121604750-1299e200-ca19-11eb-83ba-8f33e6d98b0c.png">

IGV 2.9.4

I have turned off downsampling. This is not a downsampling issue. It seems as if the rendering of part of the bottom is cut off. This is a very high-depth sample. Perhaps there is a rendering cutoff max height. Turning on squished view doesn't help.

**Comment by gevro** [comment] 2021-06-10 22:29
Note that in other samples at the bottom there is whitespace as below. But for the above sample there is gray-space.
<img width="1526" alt="Screen Shot 2021-06-10 at 6 28 36 PM" src="https://user-images.githubusercontent.com/47928628/121605066-b8e5e780-ca19-11eb-893c-61203f65b93a.png">

**Comment by jrobinso** [comment] 2021-06-11 01:02
I'm not sure what I am looking at.  Are these screenshots from the UI, or batch snapshots?

Could you extract this portion of the file into a small bam/cram and zip up a test case?  I probably can't do anything without a reproducible case.   I've not seen this before.   If you turn downsampling off you can get errors due to memory running out, if this is the case you should see something in the igv.log file.

**Comment by gevro** [comment] 2021-06-11 01:23
This is the UI, alignments view. Reproducible. SAM file here: https://www.dropbox.com/s/n9rwkfmfnjltdms/Archive.zip?dl=0
Go to chr4:55,101,763-55,102,545

Scroll down to bottom of alignments and you'll see the rendering of the reads cuts off and hits a gray zone. This is not the case in other SAM/BAM/CRAM files. I suspect the high read depth is maxing out the rendering height or something.

**Comment by jrobinso** [comment] 2021-06-11 05:17
Got it, I'll look at this when I can but no ETA at this time.  Busy busy.

**Comment by jrobinso** [comment] 2021-06-15 21:36
OK I can reproduce this now.  It looks like we are running into a limit imposed by the underlying graphic library (Swing),  the limit seems to be exactly 16kb in height.     The fix for this will take some significant redesign,  which we should do, but it won't be quick.    We'll leave this open until we have a solution.

**Comment by jrobinso** [comment] 2021-06-15 21:56
In the meantime, I suggest you enable downsampling.  You can use a large bucket size.   Alternatively you can use "Squished" view.

**Comment by gevro** [comment] 2021-06-16 01:09
Thanks. I seem to find the strangest bugs :)
How do I change the bucket size? I specifically wanted to be able to see all the reads in order to manually count some of their features.

**Comment by jrobinso** [comment] 2021-06-16 01:24
@gevro Sorry if I wasn't clear, you can't see all the reads with IGV currently, you will need to find another tool for manually counting.    When I suggested downsampling it was to see a representative sampling of the reads, rather than just the first "N".    The absolute limit of 16kb for the image will limit the number of expanded reads you can see.   But I have to ask, what are you manually counting?  That doesn't seem efficient with a depth of 1000X or more.  

You can see all the reads in "Squished" mode,  I don't know what you are counting but that probably doesn't help you.

To change downsampling options to to View > Preferences > Alignments.   I assume you have already been there to turn downsampling off or we wouldn't be having this discussion.

**Comment by gevro** [comment] 2021-06-16 01:35
Thanks. I’m counting a somatic mutation, # of occurrences in each read pair orientation. I group and color by that and count. No easy way to do that with samtools. Might be nice to have in IGV summary stats similar to +\- for strand counts per mutation. 

Squished is fine.

**Comment by jrobinso** [comment] 2021-06-16 01:43
You manually count through depths of 1000x?  I didn't really design this tool for manual analysis like that, glad it sort of works for you,  but I assume there are command line tools that do this automatically.   Perhaps I'm wrong on that.

If its a single nucleotide variant can't you get this information from the coverage track?   It will show you how many bases of each nucleotide are observed on each strand at any location.

<img width="185" alt="Screen Shot 2021-06-15 at 6 42 02 PM" src="https://user-images.githubusercontent.com/933148/122145126-7e10f480-ce09-11eb-98bd-2b9b5321a849.png">


I will eventually solve this 16kb limit but its complicated.

**Comment by gevro** [comment] 2021-06-16 10:08
That shows strand, but I am counting read pair orientation. No easy pileup tools I found can do this.

**Comment by jrobinso** [comment] 2021-06-16 16:16
Could you define more precisely what you mean by "read pair orientation"?  Do you mean read strand of first-in-pair?   Or are you using an alignment tag?

**Comment by gevro** [comment] 2021-06-16 16:24
Yes that is what I mean. Another way to refer to it is F1R2 versus F2R1.

**Comment by gevro** [comment] 2021-06-16 16:25
This can sometimes be important because it is a marker of single stranded artifacts, for example in FFPE sample sequencing.

**Comment by jrobinso** [comment] 2021-06-16 16:31
igvtools has a count-by-strand argument that might help.   From the readme

```
  --strands [arg] By default, counting is combined among both strands.
                This setting outputs the count for each strand separately.
                Legal argument values are 'read' or 'first'.
                'read' Separates count by 'read' strand, 'first' uses the first in pair strand.
                Results are saved in a separate column for .wig output, and a separate track
                for TDF output.
```

**Comment by gevro** [comment] 2021-06-16 16:36
Thanks!

**Comment by suhrig** [comment] 2021-08-19 11:45
In case this is of any help: As far as I can tell this problem first appeared with version 2.8.10. For me everything works fine in version 2.8.9. After this version, high-depth regions are cropped as described above. Tested on CentOS 7.8.

**Comment by jrobinso** [comment] 2021-09-02 04:03
@suhrig That is helpful,  did you use the embedded Java or a Java that came with the machine.  If the latter what Java vendor and version?

**Comment by suhrig** [comment] 2021-09-02 05:05
I used the embedded JRE in all cases. If this issue really is caused by a limitation of Java, then it's strange that 2.8.9 is not affected, but 2.8.10 is, because both use the same version of Java (11.0.8).

**Comment by jrobinso** [comment] 2021-09-02 15:49
Java might be the same but our use of GraphicsContext might not.  There is
a maximum size for all resources, of course.

If you don't mind me asking, what is the use case for manually scrolling
through over a thousand rows of alignments?  This bug notwithstanding there
might be a better solution.

**Comment by suhrig** [comment] 2021-09-03 08:32
> what is the use case for manually scrolling through over a thousand rows of alignments?

Visual validation of fusion-supporting reads. They often make up just a small fraction of the coverage, but they are easy to spot even among a thousand reads, because they are colorful and therefore stick out when you scroll through the reads.

**Comment by jrobinso** [comment] 2021-09-03 16:00
@suhrig In that case try "squished" view until this is fixed, you should be able to see 10,000 rows or more in that view.

**Comment by gevro** [comment] 2021-09-03 16:00
In my recollection, squished view doesn't fix the issue.

**Comment by jrobinso** [comment] 2021-09-03 19:16
@gevro How so?  You will have the same size image, its still fixed at 16kb,  but see more rows.   If this isn't your experience a test case would be helpful.

**Comment by suhrig** [comment] 2021-09-06 09:30
@jrobinso I can confirm that squished view shows more reads. However, interacting with the reads becomes cumbersome in this view. It's hard to hit the reads of interest with the mouse pointer, for example, if I want to highlight a read using Ctrl+click or if I want to right-click the read to show its mate in split view. Also, the bases become hard to identify with the human eye.

Lastly, this does not always help, for example, in the following scenario with RNA-Seq data that I just came across: There is an exon of interest covered by only about a hundred reads per base - so a manageable amount and a valid use case for IGV in my opinion. Another isoform which does not involve this exon is expressed at a much higher level. So the exon of interest is skipped by >16kb spanning reads due to splicing. In this scenario, it is impossible to inspect the reads mapping to the exon of interest, because the spanning reads fill up the entire viewable area. With older IGV versions, I could simply pull the scrollbar handle all the way to the bottom, thus skipping all spanning reads and directly jumping to the interesting reads.

**Comment by jrobinso** [comment] 2021-09-06 23:10
@suhrig Understood, the issue is still open, but this is a workaround for some.

**Closed** 2021-09-08 20:35 UTC

**Comment by jrobinso** [comment] 2021-09-08 20:48
This should be fixed now, available in the snapshot build and to be included in the next release.

@suhrig Thanks for narrowing this down to a release number, that was critical.   If anyone cares, at that release I switched from a hacked custom "layout manager" for data panels to a standard Swing one, which imposed the height limitation on the data panel alluded to earlier (16,384 pixels) based on a default max size.   The fix was to simply override this maximum height limitation.

**Comment by suhrig** [comment] 2021-09-08 20:56
Awesome, thanks for fixing!
