### ISSUE TITLE
Filter tracks function does not work

### ISSUE THREAD

**Issue by Brunox13** [igvteam/igv#941] opened 2021-03-25 02:49 UTC
I am using the IGV desktop app for Mac (v2.9.0) and I am trying to figure out how to filter BED tracks by their attributes - nothing seems to work.

I select the genome ("Human (hg38)"), then load my BED files, and then I load the associated attributes file, which seems to connect the correct attributes to the correct tracks, as I am able to display and sort by these attributes.
These same attributes even do appear in the dropdown when I go to "Tracks" > "Filter Tracks..." but when I create a filter and click "OK," nothing happens - all the tracks are always visible.
I have even tried "Reload tracks and refresh the screen" and I made sure not to have "Show all tracks" checked - but none of that helps.
Any help would be appreciated - thank you!

**Comment by jrobinso** [comment] 2021-03-25 03:33
Its working for me (v2.9.4).  If you can zip up a small test case with steps to reproduce I will look into it.

**Comment by jrobinso** [comment] 2021-03-25 03:37
Actually never mind, you said BED files.   Feature (annotation) files are not filterable,  probably they should be but there not.   I'll leave this open as a reminder to either recall why it is this way, or change it.   This has been true since IGV's initial release, so its been this way for a long time.

**Comment by Brunox13** [comment] 2021-03-25 13:44
Thanks for the reply! Is there a way for me to make these files filterable? Or which types of files actually are filterable?
I'm wondering if I can convert these BED files into something else that will be filterable.

**Comment by Brunox13** [comment] 2021-03-25 14:56
Possibly related to this, I also seemed to be unable to **overlay** different BED tracks, which would be greatly useful as well.

**Comment by jrobinso** [comment] 2021-03-25 15:44
I just pushed a change to enable filtering of bed tracks.   It will be in the next IGV release in early April.  If you need it before then you could use the "snapshot" build.   

Overlay only works for numeric (e.g. "wig", "bigwig", "tdf") tracks,  open a new issue if you would like to request this.

**Comment by jrobinso** [comment] 2021-06-15 21:02
This is now released in 2.10.0

**Closed by jrobinso** 2021-06-15 21:02 UTC
