### ISSUE TITLE
SSL handshake alert

### ISSUE THREAD

**Issue by igordot** [igvteam/igv#104] opened 2014-10-07 18:28 UTC
I am having problems loading files from https URLs. I get a "handshake alert". The error is discussed here:
http://stackoverflow.com/questions/7615645/ssl-handshake-alert-unrecognized-name-error-since-upgrade-to-java-1-7-0

The problem is fixed if I modify the java command like so:
`java -jar -Djsse.enableSNIExtension=false igv.jar`

Can the `jsse.enableSNIExtension` property be set to false in the actual Java code so that non-jar versions of IGV are fixed as well?

**Comment by jrobinso** [comment] 2015-03-20 19:41
Hi,  apologies for the delayed action.  Can you point me to a URL I can load into igv that will reproduce this problem?

**Comment by jrobinso** [comment] 2015-03-23 13:36
I tried setting the property to false in the java code, this caused SNI and 500 errors on multiple servers.  Change rolled back, it will remain unset for now.

**Comment by malcook** [comment] 2020-02-06 23:23
> The problem is fixed if I modify the java command like so:
> `java -jar -Djsse.enableSNIExtension=false igv.jar`

Happy to find this in 2020 - it works for me now as well - thanks!

**Comment by jrobinso** [comment] 2020-02-07 16:13
@malcook I've never encountered this problem, it seems to be rare, could you point me to a URL that will cause the error?

**Comment by malcook** [comment] 2020-02-07 17:18
@jrobinso 

Sure:

https://simrbase.stowers.org/sites/default/files/tripal/tripal_blast/2020Feb05_163455.blast.gff

is a blast result reformatted as gff track for a privately hosted genome which alas I can not share now.

And I have just now reconfirmed that this issue it toggled by toggling the value:

-Djsse.enableSNIExtension=true

Doe this help?

**Comment by jrobinso** [comment] 2020-02-07 17:40
@malcook Yes, it does, but its curious that there are not more reports of this.    Conservatively there has been a few million loadings from https:// urls since this was first posted.

**Comment by malcook** [comment] 2020-02-07 17:44
I expect it has as much to do with configuration of the server than anything else.

??: https://stackoverflow.com/a/41967432/415228

**Comment by jrobinso** [comment] 2020-02-07 17:49
@malcook The last time I tried to globally set this (in Java code not from the command line) it caused 500 and SNI errors on multiple servers, at the Broad and Amazon S3 for example.    But I will look at it again.    How have you managed to use IGV all these years with your simrbase host, or maybe you haven't?

**Comment by jrobinso** [comment] 2020-02-07 18:06
This does appear to be a server configuration error.  It seems wrong to globally turn this off for the sake of a few misconfigured servers.   I think I'll implement the solution here,  which will use a user provided whitelist to bypass SNI for specified hosts:  It does appear to be a host configuration problem. https://www.naschenweng.info/2017/03/31/java-bypass-sslprotocolexception-handshake-alert-unrecognized_name/

**Comment by malcook** [comment] 2020-02-07 19:28
> How have you managed to use IGV all these years with your simrbase host, or maybe you haven't

I haven't.  The SIMRBase host also implements a JBrowse|Apollo+Chado client.  This is the first time I've tried to consume its tracks in IGV.  I could first talk to the host admin if your want to learn if there is a server-side reconfig that might mitigate.  Thoughts?

**Comment by jrobinso** [comment] 2020-02-07 19:40
I'm not expert enough on this to help your administrator.    You might refer your admin to this for a start:  https://www.naschenweng.info/2017/03/31/java-bypass-sslprotocolexception-handshake-alert-unrecognized_name/.   BTW the solution I posted above doesn't work > Java 8.   Your command line advice is likely to be the "fix" for anyone experiencing this problem.   Again its rare most servers are apparently properly configured as this problem has been reported twice now in 6 years.

**Comment by jrobinso** [comment] 2020-02-07 21:00
@malcook ignore the java post above, much better explanation here.  I suggest passing this on to your admin.  The server_name warning is ignored by browsers, but treated as an error by Java.   https://discussions.qualys.com/thread/13532

**Comment by jrobinso** [comment] 2020-02-07 21:09
Closing this now, there is nothing I can safely do in Java 11 to deal with this, other than globally disabling the SNI extension for all hosts.  This can cause issues at hosts that require it.

**Closed by jrobinso** 2020-02-07 21:09 UTC
