### ISSUE TITLE
Using port/url to open and navigate bam files, behavior different with versions prior to 2.12

### ISSUE THREAD

**Issue by carolynlawrence** [igvteam/igv#1179] opened 2022-08-08 21:34 UTC
We are using the IGV "listen on port" option to open bam files in IGV. Our links to open files look like this:
http://localhost:60151/load?file=\\some_locally_accessible_server_directory\my_bamfile.bam&genome=hg19&locus=chr3:41266125

This works fine, but we recently noticed on some computers the behavior is different, and we isolated this to the IGV version:

Behavior 1: In versions prior to 2.12 (e.g. in 2.11.9), if we click multiple links that correspond to the same .bam file, but different locations, we only end up with one set of tracks. E.g. if the first link clicked has locus=chr3:41266125, and the next has locus=chr5:1234567, the chr3 tracks are removed and we only see those for the latest (chr5) location.

Behavior 2: In versions 2.12+, we just get more and more tracks loaded into the same IGV window, so for the example above we'd see both the tracks corresponding to the chr3 location, and another set for chr5, and more if we clicked on more variants/loci, even though all correspond to the same .bam file.

I'm not sure if this is a bug, or an intentional change. However behavior 1 is the desired behavior for our use case. So we are left with either downgrading our version, or having to continually remove the old tracks.

If this isn't a bug, is there a way to make an option in the preferences that enables the older behavior?

Thanks!

**Comment by jrobinso** [comment] 2022-08-08 22:03
IIRC the previous behavior was considered a bug by some because it was impossible to load the same file twice, for example to compare different coloring options.   The command you reference literally says to load a track,  genome, then jump to a locus.    But yes I will consider a preference to restore the old behavior, or perhaps an extra URL parameter to specify an explicit load, with the old behavior the default.

This can be un-ambiguously fixed by separating your links by intent, for example

* Load, set genome

http://localhost:60151/load?file=\\some_locally_accessible_server_directory\my_bamfile.bam&genome=hg19

* Navigate

http://localhost:60151/goto?locus=chr3:41266125
http://localhost:60151/goto?locus=MYC

**Comment by carolynlawrence** [comment] 2022-08-09 16:29
@jrobinso Thanks so much for the quick reply!

I see what you are saying with the two different types of links. Our workflow is that we have a large batches of samples each week, and for each sample a webpage of variant results for analysis where the links are auto-generated for each variant identified. We could theoretically have one link to open the sample in IGV, then have the auto-generated links be of the navigation variety, but we would then run the risk of a user forgetting to open the new bam file when they switch to analyze the next sample, so they'd be looking at the right location in the wrong sample- which would end up leading to confusion and likely be a lot more trouble than having to remove a few tracks. 

Now that we've figured out what was happening, we can work around it, but it would be awesome if you could add in an extra URL parameter that would let us use the old behavior!

**Comment by jrobinso** [comment] 2022-08-09 16:45
@carolynlawrence My plan is to add an explicit parameter if you want to load a file multiple times, perhaps ```dup=true```, in thinking about this I think your case is the most common.   The change was not specifically targeting links, it was a lower level change to allow loading a file multiple times by any means.   The change to link behavior was a side effect.   Leave this issue open until that is addressed.

BTW this is unrelated but igv.js and igv-webapp supports this type of use case without the need for users to install the desktop application.   For example [https://igv.org/app/?file=https://s3.amazonaws.com/igv.org.test/data/gm12878_loops.bedpe.gz&locus=chr1&name=GM12878+loops](https://igv.org/app/?file=https://s3.amazonaws.com/igv.org.test/data/gm12878_loops.bedpe.gz&locus=chr1&name=GM12878+loops).

**Closed** 2022-08-31 18:30 UTC

**Comment by jrobinso** [comment] 2025-07-02 16:39
Which version are you testing?

**Comment by jrobinso** [comment] 2025-07-02 21:23
Well we can't really look into problems on version 2.16.1.     If this can be reproduced in the latest release (2.19.4) please either reopen this issue,  or create a new one focused on the problem you are having.

**Comment by muhligs** [comment] 2025-07-03 07:01
I understand. Thanks. I checked the linux igv 2.19.4, and things worked with the NA12877_S1.bam. 
Since I can't control the versions of my end users, I will go with separate load data and goto buttons. 

Thanks for your efforts with IGV.
